#!/bin/bash
# =============================================================================
# Treble Overlay Build Script
# =============================================================================
# Reads config.env for device-specific settings, then:
#   1. Backs up current config/vendor/sepolicy to YOUR BACKUPS/
#   2. Generates AndroidManifest.xml files from config.env
#   3. Generates resource XML (res/values/generated.xml) from config.env
#   4. Compiles overlay resources with aapt2
#   5. Zipaligns and signs the APKs
#   6. Auto-generates customize.sh and service.sh from config.env + vendor/
#   7. Packages a KSU/Magisk flashable module
#
# If config.env doesn't exist, the script will:
#   1. Ask if you want to use config.env.example (if found) for testing
#   2. If yes, copy it and proceed with the build
#   3. If no, generate a placeholder config and exit for you to edit
#
# Usage: ./build.sh
#
# Requirements: aapt2, zipalign, apksigner, framework-res.apk
#
# Quick setup:
#   ./setup.sh                    # Auto-downloads/installs everything
#
# Or manually (Debian/Ubuntu):
#   sudo apt install aapt android-sdk-build-tools apksigner android-framework-res
#
# Or manually (other distros):
#   See vendor_extraction_guide.md for platform-specific instructions
# =============================================================================

set -e
set -o pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Local tools directory support ──────────────────────────────────────────
# If tools/ exists, prepend to PATH so aapt2, zipalign, apksigner are found.
# This allows setup.sh to install tools locally without sudo.
if [ -d "${SCRIPT_DIR}/tools" ]; then
    export PATH="${SCRIPT_DIR}/tools:${PATH}"
fi

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
info() { echo -e "  ${YELLOW}→${NC} $*"; }
err()  { echo -e "  ${RED}✗${NC} $*" >&2; }
step() { echo -e "\n${BOLD}━━━ $* ━━━${NC}"; }

# ---------------------------------------------------------------------------
# Backup helper
# ---------------------------------------------------------------------------
BACKUP_DIR="YOUR BACKUPS"
do_backup() {
    mkdir -p "$BACKUP_DIR"
    local backed_up=false
    [ -f "config.env" ]            && { cp config.env "$BACKUP_DIR/config.env";            ok "Backed up config.env";            backed_up=true; }
    [ -f "sepolicy.rule" ]         && { cp sepolicy.rule "$BACKUP_DIR/sepolicy.rule";      ok "Backed up sepolicy.rule";      backed_up=true; }
    [ -d "system/vendor" ]         && { rm -rf "$BACKUP_DIR/vendor"; cp -r system/vendor "$BACKUP_DIR/vendor"; ok "Backed up system/vendor/"; backed_up=true; }
    [ -f "customize.sh" ]          && { cp customize.sh "$BACKUP_DIR/customize.sh";        ok "Backed up customize.sh";       backed_up=true; }
    [ -f "service.sh" ]            && { cp service.sh "$BACKUP_DIR/service.sh";            ok "Backed up service.sh";         backed_up=true; }
    echo ""
    $backed_up && info "Backup saved to ${BACKUP_DIR}/" || info "Nothing to back up"
}

# ---------------------------------------------------------------------------
# Resource XML auto-generator — applies config.env values to overlay resources
# Generates res/values/generated.xml which overrides config.xml/bools.xml/dimens.xml
# ---------------------------------------------------------------------------
generate_resource_xml() {
    local gen="res/values/generated.xml"

    cat > "$gen" << 'GENEOF'
<?xml version="1.0" encoding="utf-8"?>
<!--
    Auto-generated by build.sh from config.env — DO NOT EDIT BY HAND.
    Edit config.env and re-build. Overrides values in config.xml, bools.xml,
    and dimens.xml based on your config.env settings.
-->
<resources>

GENEOF

    # ── Feature flags (bools) ────────────────────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_supportsUdfps">true</bool>
    <bool name="config_supportsScreenOffUdfps">true</bool>

GENEOF
    fi

    if [ "$HAS_AOD" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dozeAlwaysOnDisplayAvailable">true</bool>

GENEOF
    fi

    if [ "$HAS_DOZE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dozeAfterScreenOffByDefault">true</bool>
    <bool name="config_dozePulsePickup">true</bool>

GENEOF
    fi

    if [ "$HAS_AUTO_BRIGHTNESS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_automatic_brightness_available">true</bool>

GENEOF
    fi

    if [ "$HAS_BURN_IN_PROTECTION" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_enableBurnInProtection">true</bool>
    <bool name="config_statusBarBurnInProtection">true</bool>

GENEOF
    fi

    if [ "$HAS_DOUBLE_TAP_WAKE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_supportDoubleTapWake">true</bool>

GENEOF
    if [ "$HAS_HBM" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dynamic_automatic_brightness_available">true</bool>
    <integer name="config_screenBrightnessExtendedMaximum">${BRIGHTNESS_EXTENDED_MAXIMUM}</integer>

GENEOF
    fi

    fi

    if [ "$HAS_5G" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_telephony5gNonStandalone">true</bool>

GENEOF
    fi

    if [ "$HAS_VOLTE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_device_volte_available">true</bool>
    <bool name="config_device_vt_available">true</bool>
    <bool name="config_device_wfc_ims_available">true</bool>

GENEOF
    fi

    # ── Corner radius (dimen) ────────────────────────────────────────────
    cat >> "$gen" << GENEOF
    <dimen name="rounded_corner_radius">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_radius_top">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_radius_bottom">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius_top">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius_bottom">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_content_padding">0px</dimen>

GENEOF

    # ── Status bar height (dimen) ────────────────────────────────────────
    cat >> "$gen" << GENEOF
    <dimen name="status_bar_height">${STATUS_BAR_HEIGHT}.0px</dimen>
    <dimen name="status_bar_height_portrait">${STATUS_BAR_HEIGHT}.0px</dimen>

GENEOF

    # ── Light sensor type (string) ───────────────────────────────────────
    cat >> "$gen" << GENEOF
    <string name="config_displayLightSensorType" translatable="false">${LIGHT_SENSOR_TYPE}</string>

GENEOF

    # ── Brightness (integers + float items) ──────────────────────────────
    cat >> "$gen" << GENEOF
    <integer name="config_screenBrightnessDim">${BRIGHTNESS_DIM}</integer>
    <integer name="config_screenBrightnessDark">${BRIGHTNESS_DARK}</integer>
    <integer name="config_screenBrightnessDoze">${BRIGHTNESS_DOZE}</integer>
    <integer name="config_screenBrightnessSettingMinimum">${BRIGHTNESS_MIN}</integer>
    <integer name="config_screenBrightnessSettingDefault">${BRIGHTNESS_DEFAULT}</integer>
    <integer name="config_screenBrightnessSettingMaximum">${BRIGHTNESS_MAX}</integer>

GENEOF

    # Compute float equivalents (approximate)
    local doze_float=$(echo "scale=8; $BRIGHTNESS_DOZE / 255" | bc 2>/dev/null || echo "0.23529412")
    local dim_float=$(echo "scale=8; $BRIGHTNESS_DIM / 255" | bc 2>/dev/null || echo "0.050980393")
    local min_float=$(echo "scale=8; $BRIGHTNESS_MIN / 255" | bc 2>/dev/null || echo "0.0")
    local default_float=$(echo "scale=8; $BRIGHTNESS_DEFAULT / 255" | bc 2>/dev/null || echo "0.5019608")
    local max_float=$(echo "scale=8; $BRIGHTNESS_MAX / 255" | bc 2>/dev/null || echo "1.0")

    cat >> "$gen" << GENEOF
    <item name="config_screenBrightnessDozeFloat" format="float" type="dimen">${doze_float}</item>
    <item name="config_screenBrightnessDimFloat" format="float" type="dimen">${dim_float}</item>
    <item name="config_screenBrightnessSettingMinimumFloat" format="float" type="dimen">${min_float}</item>
    <item name="config_screenBrightnessSettingDefaultFloat" format="float" type="dimen">${default_float}</item>
    <item name="config_screenBrightnessSettingMaximumFloat" format="float" type="dimen">${max_float}</item>

GENEOF

    # ── Refresh rate (integers) ──────────────────────────────────────────
    cat >> "$gen" << GENEOF
    <integer name="config_defaultRefreshRate">${DEFAULT_REFRESH_RATE}</integer>
    <integer name="config_defaultPeakRefreshRate">${PEAK_REFRESH_RATE}</integer>

GENEOF

    # ── UDFPS sensor position (integer-array) ────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <integer-array name="config_udfps_sensor_props">
        <item>${UDFPS_X}</item>
        <item>${UDFPS_Y}</item>
        <item>${UDFPS_RADIUS}</item>
    </integer-array>

GENEOF
    fi

    # Close resources
    echo "</resources>" >> "$gen"

    local val_count=$(grep -c '<\(bool\|dimen\|integer\|string\|item\|integer-array\) ' "$gen" 2>/dev/null || echo "0")
    ok "Generated: res/values/generated.xml (${val_count} resource values from config.env)"
}

# ---------------------------------------------------------------------------
# SystemUI overlay resource generator
# Generates systemui_overlay/res/values/generated.xml for doze/AOD behavior
# ---------------------------------------------------------------------------
generate_systemui_resource_xml() {
    local gen="systemui_overlay/res/values/generated.xml"
    mkdir -p "$(dirname "$gen")"

    # doze_display_state_supported: true if HAS_AOD, else false
    local doze_state
    local doze_suspend_state

    if [ "$HAS_AOD" = "true" ]; then
        doze_state="true"
    else
        doze_state="false"
    fi

    # doze_suspend_display_state_supported: false if DOZE_SUSPEND is broken
    # (Samsung hwcomposer issue). Set DOZE_SUSPEND_UNSUPPORTED=true in config.env
    if [ "$DOZE_SUSPEND_UNSUPPORTED" = "true" ]; then
        doze_suspend_state="false"
    else
        doze_suspend_state="true"
    fi

    cat > "$gen" << GENEOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by build.sh from config.env — DO NOT EDIT BY HAND. -->
<resources>
    <bool name="doze_display_state_supported">${doze_state}</bool>
    <bool name="doze_suspend_display_state_supported">${doze_suspend_state}</bool>
    <bool name="doze_proximity_check_before_pulse">false</bool>
    <bool name="doze_pickup_performs_proximity_check">false</bool>
</resources>
GENEOF

    local sysui_count=$(grep -c '<bool ' "$gen" 2>/dev/null || echo "0")
    ok "Generated: systemui_overlay/res/values/generated.xml (${sysui_count} resource values)"
}

# ---------------------------------------------------------------------------
# Service.sh auto-generator — creates post-boot init script from config.env
# ---------------------------------------------------------------------------
generate_service_sh() {
    local target="$1"

    cat > "$target/service.sh" << 'SERVEOF'
#!/sbin/sh
# =============================================================================
# Treble Overlay — Post-Boot Initialization Script
# =============================================================================
# Auto-generated by build.sh from config.env.
# Edit config.env and re-build to change these values.
#
# For vendor-specific additions (Samsung IMS, custom HAL startup, etc.):
#   Place a service.sh at the project root with your customizations.
#   build.sh will detect it and use it instead of auto-generating.
#   See service.sh.example for a reference (Samsung Galaxy A90 5G).
# =============================================================================

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 1: Wait for boot
# ═══════════════════════════════════════════════════════════════════════════
SERVEOF

    cat >> "$target/service.sh" << 'SERVEOF'
while [ "$(getprop sys.boot_completed)" != "1" ]; do
    sleep 5
done

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 2: Enable overlays
# ═══════════════════════════════════════════════════════════════════════════
cmd overlay enable @OVERLAY_PACKAGE@ 2>/dev/null || true
cmd overlay enable @OVERLAY_PACKAGE_SYSTEMUI@ 2>/dev/null || true

SERVEOF

    # ── SECTION 3: AOD / Doze ──────────────────────────────────────────────
    if [ "$HAS_AOD" = "true" ] || [ "$HAS_DOZE" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 3: AOD / Doze configuration
# ═══════════════════════════════════════════════════════════════════════════
setprop persist.sys.overlay.aod true
setprop persist.sys.phh.disable_display_doze_suspend true

SERVEOF
    fi

    # ── SECTION 4: UDFPS properties ─────────────────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        local udfps_size=$UDFPS_RADIUS
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 4: UDFPS Fingerprint properties
# ═══════════════════════════════════════════════════════════════════════════
setprop persist.sys.udfps.custom 1
SERVEOF

        cat >> "$target/service.sh" << SERVEOF
setprop persist.sys.udfps.x ${UDFPS_X}
setprop persist.sys.udfps.y ${UDFPS_Y}
setprop persist.sys.udfps.size ${UDFPS_RADIUS}

SERVEOF

        # Samsung-specific fingerprint flag
        if [ "$HAS_SAMSUNG_FINGERPRINT" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.sys.phh.samsung_fingerprint 1

SERVEOF
        fi
    fi

    # ── SECTION 5: Vendor HAL services ──────────────────────────────────────
    local has_hal=false
    if [ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ] || [ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ]; then
        has_hal=true
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 5: Vendor HAL services
# ═══════════════════════════════════════════════════════════════════════════
# Start vendor HAL services if their binaries exist in the module.
# Add custom HAL starts here or place a service.sh at project root.
# =========================================================================

# Scan for available HAL binaries and start their services.
# Service names are derived from .rc files in system/vendor/etc/init/.
SERVEOF

        if [ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
# --- Fingerprint HAL ---
# Uncomment and adjust the binary path to match YOUR device's fingerprint HAL.
# Reference: /system/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.3-service.samsung
for fp_hal in /system/vendor/bin/hw/android.hardware.biometrics.fingerprint*; do
    if [ -f "$fp_hal" ]; then
        # Try common service names
        for svc in vendor.fps_hal_aosp vendor.fps_hal vendor.fingerprint; do
            /system/bin/start "$svc" 2>/dev/null && break || true
        done
    fi
    break
done 2>/dev/null || true

SERVEOF
        fi

        if [ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
# --- Vibrator HAL ---
# Uncomment and adjust for your device's vibrator HAL.
# Reference: /system/vendor/bin/hw/vendor.samsung.hardware.vibrator@2.2-service
for vib_hal in /system/vendor/bin/hw/*vibrat*; do
    if [ -f "$vib_hal" ]; then
        for svc in sec-vibrator-2-2 vendor.vibrator vibrator; do
            /system/bin/start "$svc" 2>/dev/null && break || true
        done
    fi
    break
done 2>/dev/null || true

SERVEOF
        fi
    fi

    # ── SECTION 6: Samsung FOD (Fingerprint on Display) enable ───────────────
    if [ "$HAS_SAMSUNG_FOD" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 6: Samsung FOD (Fingerprint on Display) enable
# ═══════════════════════════════════════════════════════════════════════════
# Enables FOD mode on the TSP (Touch Screen Panel). The TSP driver lights
# up the sensor area when the fingerprint HAL activates. Without this,
# the sensor area stays dark and UDFPS will not work.

TSP_SYS="/sys/class/sec/tsp/cmd"
if [ -f "$TSP_SYS" ]; then
    chmod 0660 "$TSP_SYS" 2>/dev/null || true
    if echo "fod_enable,1" > "$TSP_SYS" 2>/dev/null; then
        log -t "treble-overlay" "  ✓ FOD enabled via $TSP_SYS" || true
        setprop persist.sys.phh.fod_enabled 1
    else
        log -t "treble-overlay" "  ✗ Failed to write FOD enable (SELinux?)" || true
    fi
else
    log -t "treble-overlay" "  - TSP sysfs not found at $TSP_SYS" || true
fi

SERVEOF
    fi

    # ── SECTION 7: Samsung Vibrator HAL start ────────────────────────────────
    if [ "$HAS_SAMSUNG_VIBRATOR" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 7: Samsung Vibrator HAL — start existing vendor service
# ═══════════════════════════════════════════════════════════════════════════
# Stock Samsung vendor has vibrator HAL at:
#   /vendor/bin/hw/vendor.samsung.hardware.vibrator@2.2-service
# Service name: sec-vibrator-2-2 (defined in vendor/etc/init/*.rc)

VIB_SERVICE="sec-vibrator-2-2"

if [ -n "$(getprop init.svc.$VIB_SERVICE 2>/dev/null)" ]; then
    if [ "$(getprop init.svc.$VIB_SERVICE)" != "running" ]; then
        log -t "treble-overlay" "  Starting: $VIB_SERVICE" || true
        start $VIB_SERVICE 2>/dev/null || true
        sleep 1
        if [ "$(getprop init.svc.$VIB_SERVICE)" = "running" ]; then
            log -t "treble-overlay" "  ✓ Vibrator HAL started" || true
            setprop persist.sys.phh.vibrator_started 1
        else
            log -t "treble-overlay" "  ✗ Vibrator HAL failed to start" || true
        fi
    else
        log -t "treble-overlay" "  ✓ Vibrator HAL already running" || true
        setprop persist.sys.phh.vibrator_started 1
    fi
fi

SERVEOF
    fi

    # ── SECTION 8: Samsung device node permissions for fingerprint ───────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 8: Samsung device node permissions for fingerprint
# ═══════════════════════════════════════════════════════════════════════════
# These are normally done by vendor/etc/init/fingerprint_common.rc
# on the `on boot` trigger. On GSIs, we set them here to be safe.

# Samsung ESFP (Exynos Security FingerPrint) device node
if [ -e "/dev/esfp0" ]; then
    chmod 0660 /dev/esfp0 2>/dev/null || true
    chown system system /dev/esfp0 2>/dev/null || true
fi

# Goodix fingerprint device node
if [ -e "/dev/goodix_fp" ]; then
    chmod 0660 /dev/goodix_fp 2>/dev/null || true
    chown system system /dev/goodix_fp 2>/dev/null || true
fi

# Sysfs fingerprint node ownership
FP_SYSFS="/sys/class/fingerprint/fingerprint"
if [ -d "$FP_SYSFS" ]; then
    for node in type_check name vendor adm bfs_values position cbgecnt intcnt resetcnt wuhbtest rb; do
        if [ -f "$FP_SYSFS/$node" ]; then
            chown system radio "$FP_SYSFS/$node" 2>/dev/null || true
        fi
    done
fi

# Data directories for fingerprint template storage
for dir in /data/vendor/misc /data/vendor/misc/qti_fp /data/vendor/misc/qti_fp/bg_estimation /data/vendor/misc/qti_fp/calib_test /data/vendor/misc/qti_fp/template /data/vendor/biometrics /data/vendor/fpSnrTest; do
    [ -d "$dir" ] && chmod 0770 "$dir" 2>/dev/null || true
done

SERVEOF
    fi

    # ── SECTION 6: Connectivity (5G / VoLTE) ────────────────────────────────
    if [ "$HAS_5G" = "true" ] || [ "$HAS_VOLTE" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 6: Connectivity (5G / VoLTE)
# ═══════════════════════════════════════════════════════════════════════════
SERVEOF

        if [ "$HAS_5G" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.sys.phh.force_display_5g 1
setprop persist.sys.phh.radio.nr 1

SERVEOF
        fi

        if [ "$HAS_VOLTE" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.dbg.volte_avail_ovr 1
setprop persist.dbg.allow_ims_off 0
settings put global preferred_network_mode 26

SERVEOF
        fi
    fi

    # ── SECTION 7: Brightness / panel-specific fixes ────────────────────────
    # This section is generic — Samsung users should add full_brightness
    # via a custom service.sh at project root or service.sh.example.
    cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 7: Device-specific properties
# ═══════════════════════════════════════════════════════════════════════════
# Add vendor-specific setprop calls below.
# For Samsung panels, uncomment:
#   setprop persist.sys.samsung.full_brightness true
#   setprop persist.sys.qcom-brightness -1
# =========================================================================

SERVEOF

    # Close
    chmod +x "$target/service.sh"
    local svc_count=5
    [ "$HAS_UDFPS" = "true" ] && svc_count=$((svc_count + 2))
    [ "$HAS_AOD" = "true" ] && svc_count=$((svc_count + 1))
    [ "$HAS_5G" = "true" ] && svc_count=$((svc_count + 1))
    [ "$HAS_VOLTE" = "true" ] && svc_count=$((svc_count + 1))
    [ "$has_hal" = "true" ] && svc_count=$((svc_count + 1))

    info "service.sh auto-generated (${svc_count} sections)"
}

# ---------------------------------------------------------------------------
# customize.sh auto-generator
# ---------------------------------------------------------------------------
generate_customize_sh() {
    local target="$1"
    cat > "$target/customize.sh" << 'CUSTOMIZE_EOF'
#!/sbin/sh
# =============================================================================
# Treble Overlay — KSU/Magisk Module Install Script
# =============================================================================
# Auto-generated by build.sh from system/vendor/ contents.
# Edit the template in "TEMPLATE RECOVERIES (Don't touch)/customize.sh"
# and place it at project root if you need custom SELinux contexts.
# =============================================================================

MODPATH=${0%/*}

ui_print "  Installing ${MODPATH##*/}..."

# ── Overlay APKs ──────────────────────────────────────────────────────────
set_perm_recursive $MODPATH/system/product/overlay 0 0 0644 u:object_r:system_file:s0

CUSTOMIZE_EOF

    # Vendor HAL binaries
    if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_BIN'

# ── Vendor HAL binaries ───────────────────────────────────────────────────
CUSTOMIZE_BIN
        for f in system/vendor/bin/hw/*; do
            [ -f "$f" ] || continue
            local name
            name=$(basename "$f")
            cat >> "$target/customize.sh" << CUSTOMIZE_BIN_ITEM
if [ -f "\\$MODPATH/system/vendor/bin/hw/$name" ]; then
    set_perm \\$MODPATH/system/vendor/bin/hw/$name 0 2000 0755 u:object_r:vendor_file:s0
    ui_print "  • HAL: $name"
fi

CUSTOMIZE_BIN_ITEM
        done
    fi

    # Shared libraries
    if [ -d "system/vendor/lib64" ] && [ "$(ls -A system/vendor/lib64/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_LIB'

# ── Shared libraries ──────────────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/lib64" ]; then
    set_perm_recursive $MODPATH/system/vendor/lib64 0 0 0644 u:object_r:vendor_file:s0
    ui_print "  • Vendor shared libraries set"
fi

CUSTOMIZE_LIB
    fi

    # Init .rc files
    if [ -d "system/vendor/etc/init" ] && [ "$(ls -A system/vendor/etc/init/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_RC'

# ── Init .rc files ────────────────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/etc/init" ]; then
    for rc in $MODPATH/system/vendor/etc/init/*.rc; do
        [ -f "$rc" ] && set_perm "$rc" 0 0 0644 u:object_r:vendor_configs_file:s0
    done
    ui_print "  • Init .rc files set ($(ls $MODPATH/system/vendor/etc/init/*.rc 2>/dev/null | wc -l) files)"
fi

CUSTOMIZE_RC
    fi

    # VINTF manifest fragments
    if [ -d "system/vendor/etc/vintf/manifest" ] && [ "$(ls -A system/vendor/etc/vintf/manifest/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_VINTF'

# ── VINTF manifest fragments ──────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/etc/vintf/manifest" ]; then
    for xml in $MODPATH/system/vendor/etc/vintf/manifest/*.xml; do
        [ -f "$xml" ] && set_perm "$xml" 0 0 0644 u:object_r:vendor_configs_file:s0
    done
    ui_print "  • VINTF manifest files set ($(ls $MODPATH/system/vendor/etc/vintf/manifest/*.xml 2>/dev/null | wc -l) files)"
fi

CUSTOMIZE_VINTF
    fi

    # Done banner
    cat >> "$target/customize.sh" << 'CUSTOMIZE_END'

# ── Done ──────────────────────────────────────────────────────────────────
ui_print "  ✓ Module installed successfully!"
CUSTOMIZE_END

    chmod +x "$target/customize.sh"
}

# ---------------------------------------------------------------------------
# Load or create config
# ---------------------------------------------------------------------------
CONFIG_FILE="config.env"

if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "\n${YELLOW}No config.env found.${NC}\n"

    USE_EXAMPLE=false
    if [ -f "config.env.example" ]; then
        echo -e "  ${BOLD}Use example config (config.env.example) for testing?${NC}"
        echo -e "  This will pre-fill values for the Samsung Galaxy A90 5G as a reference."
        read -r -p "  [y/N] " use_example
        echo ""
        if [[ "$use_example" =~ ^[Yy]$ ]]; then
            cp config.env.example config.env
            echo -e "  ${GREEN}✓${NC} Copied config.env.example → config.env"
            echo -e "  ${YELLOW}→${NC} Proceeding with build using example values...\n"
            USE_EXAMPLE=true
        fi
    fi

    if [ "$USE_EXAMPLE" != "true" ]; then
        echo -e "  ${YELLOW}Generating placeholder config.env — edit it for YOUR device, then re-run.${NC}\n"

        cat > "$CONFIG_FILE" << 'DEFAULT_CONFIG'
# =============================================================================
# Treble Overlay — Device Configuration
# =============================================================================
# Edit this file to match YOUR device, then run: ./build.sh
#
# Steps:
#   1. Change OVERLAY_NAME to something unique for your device
#   2. Set DEVICE_PROP_VALUE to your device's codename
#   3. Adjust display/UDFPS values for your hardware
#   4. Set feature flags for your device
#   5. Optionally add vendor HAL files (see vendor_extraction_guide.md)
#   6. Run: ./build.sh
#
# Example reference: Samsung Galaxy A90 5G — see config.env.example
# =============================================================================

OVERLAY_NAME="treble-overlay-<device_manufacturer>-<device_codename>"
OVERLAY_PACKAGE="me.phh.treble.overlay.<device_codename>"
OVERLAY_PACKAGE_SYSTEMUI="me.phh.treble.overlay.<device_codename>.systemui"
DEVICE_PROP_NAME="ro.product.device"
DEVICE_PROP_VALUE="<device_codename>"
COMPILE_SDK_VERSION=36
ANDROID_VERSION="16"
MIN_SDK_VERSION=35
TARGET_SDK_VERSION=35
OVERLAY_PRIORITY=628
OVERLAY_PRIORITY_SYSTEMUI=9999
DEVICE_MANUFACTURER="<device_manufacturer>"
DEVICE_MODEL="<device_model>"
DEVICE_CODENAME="<device_codename>"
ROUNDED_CORNER_RADIUS=100
STATUS_BAR_HEIGHT=76
HAS_UDFPS=false
UDFPS_X=540
UDFPS_Y=2145
UDFPS_RADIUS=114
HAS_SAMSUNG_FINGERPRINT=false
HAS_AUTO_BRIGHTNESS=true
LIGHT_SENSOR_TYPE="<sensor_name>"
DEFAULT_REFRESH_RATE=60
PEAK_REFRESH_RATE=60
BATTERY_CAPACITY=4000
BATTERY_TYPICAL_CAPACITY=4000
BRIGHTNESS_DIM=15
BRIGHTNESS_DARK=3
BRIGHTNESS_DOZE=60
BRIGHTNESS_DEFAULT=128
BRIGHTNESS_MIN=0
BRIGHTNESS_MAX=255
HAS_AOD=false
HAS_DOZE=false
DOZE_SUSPEND_UNSUPPORTED=false
HAS_5G=false
HAS_VOLTE=false
HAS_BURN_IN_PROTECTION=false
HAS_DOUBLE_TAP_WAKE=false
HAS_VENDOR_FINGERPRINT_HAL=false
HAS_VENDOR_VIBRATOR_HAL=false
PLATFORM_JAR="/usr/share/android-framework-res/framework-res.apk"
PLATFORM_KEY="keys/platform.pk8"
PLATFORM_CERT="keys/platform.x509.pem"
DEFAULT_CONFIG

        echo -e "  ${YELLOW}→${NC} Created ${BOLD}$CONFIG_FILE${NC} with placeholder values."
        echo -e "  ${YELLOW}→${NC} Edit it for your device, then re-run: ${BOLD}./build.sh${NC}"
        exit 0
    fi
fi

source "$CONFIG_FILE"

# Validate required values (should always be set, even if placeholders)
[ -z "$OVERLAY_NAME" ] && { err "OVERLAY_NAME not set in config.env"; exit 1; }
[ -z "$DEVICE_PROP_VALUE" ] && { err "DEVICE_PROP_VALUE not set in config.env"; exit 1; }

# ---------------------------------------------------------------------------
# Device identity check — only check the key codename values
# ---------------------------------------------------------------------------
# Identity variables that define WHICH device this overlay targets.
IDENTITY_VARS=("OVERLAY_NAME" "OVERLAY_PACKAGE" "OVERLAY_PACKAGE_SYSTEMUI" \
               "DEVICE_PROP_VALUE" "DEVICE_MANUFACTURER" "DEVICE_MODEL" "DEVICE_CODENAME")

has_placeholder=false
for var_name in "${IDENTITY_VARS[@]}"; do
    val="${!var_name}"
    if [[ "$val" == *"<"* ]]; then
        has_placeholder=true
        break
    fi
done

if $has_placeholder; then
    echo ""
    echo -e "  ${YELLOW}┌──────────────────────────────────────────────────────────┐${NC}"
    echo -e "  ${YELLOW}│${NC}  ⚠  Device codename not configured yet!                ${YELLOW}│${NC}"
    echo -e "  ${YELLOW}│${NC}                                                       ${YELLOW}│${NC}"
    echo -e "  ${YELLOW}│${NC}  The following values still have placeholders:         ${YELLOW}│${NC}"
    for var_name in "${IDENTITY_VARS[@]}"; do
        val="${!var_name}"
        if [[ "$val" == *"<"* ]]; then
            printf "  ${YELLOW}│${NC}    %-30s = %-20s ${YELLOW}│${NC}\n" "$var_name" "$val"
        fi
    done
    echo -e "  ${YELLOW}│${NC}                                                       ${YELLOW}│${NC}"
    echo -e "  ${YELLOW}│${NC}  You need to edit config.env and set your device info. ${YELLOW}│${NC}"
    echo -e "  ${YELLOW}└──────────────────────────────────────────────────────────┘${NC}"
    echo ""
    echo -e "  ${BOLD}[1]${NC} Generate with generic values (for quick testing only)"
    echo -e "  ${BOLD}[2]${NC} Cancel and edit config.env"
    echo ""
    read -r -p "  Choose [1/2]: " placeholder_choice

    if [[ "$placeholder_choice" != "1" ]]; then
        echo ""
        echo -e "  ${YELLOW}→${NC} Edit config.env with your device's values, then re-run: ${BOLD}./build.sh${NC}"
        echo ""
        exit 0
    fi

    echo ""
    info "Using generic values for this build (placeholder -> safe default):"
    echo ""

    # Apply generic safe defaults for identity vars
    [[ "${OVERLAY_NAME}" == *"<"* ]]             && OVERLAY_NAME="treble-overlay-generic"             && info "  OVERLAY_NAME         → treble-overlay-generic"
    [[ "${OVERLAY_PACKAGE}" == *"<"* ]]           && OVERLAY_PACKAGE="me.phh.treble.overlay.generic"    && info "  OVERLAY_PACKAGE       → me.phh.treble.overlay.generic"
    [[ "${OVERLAY_PACKAGE_SYSTEMUI}" == *"<"* ]] && OVERLAY_PACKAGE_SYSTEMUI="me.phh.treble.overlay.generic.systemui" && info "  OVERLAY_PACKAGE_SYS...→ me.phh.treble.overlay.generic.systemui"
    [[ "${DEVICE_PROP_VALUE}" == *"<"* ]]         && DEVICE_PROP_VALUE="generic"                       && info "  DEVICE_PROP_VALUE     → generic"
    [[ "${DEVICE_MANUFACTURER}" == *"<"* ]]       && DEVICE_MANUFACTURER="Generic"                     && info "  DEVICE_MANUFACTURER   → Generic"
    [[ "${DEVICE_MODEL}" == *"<"* ]]              && DEVICE_MODEL="Generic Device"                     && info "  DEVICE_MODEL          → Generic Device"
    [[ "${DEVICE_CODENAME}" == *"<"* ]]           && DEVICE_CODENAME="generic"                         && info "  DEVICE_CODENAME       → generic"

    # Also handle LIGHT_SENSOR_TYPE since it commonly has a placeholder too
    [[ "${LIGHT_SENSOR_TYPE}" == *"<"* ]]         && LIGHT_SENSOR_TYPE="android.sensor.light"           && info "  LIGHT_SENSOR_TYPE     → android.sensor.light"
    echo ""
    echo -e "  ${YELLOW}⚠  These are TEST values. Edit config.env for real device values.${NC}"
    echo ""
else
    # All identity values are filled — show summary and confirm
    echo ""
    echo -e "  ${GREEN}┌──────────────────────────────────────────────────────────┐${NC}"
    echo -e "  ${GREEN}│${NC}  Device configuration detected                       ${GREEN}│${NC}"
    echo -e "  ${GREEN}└──────────────────────────────────────────────────────────┘${NC}"
    echo ""
    echo -e "  ${BOLD}Identity:${NC}"
    echo "    Device:        ${DEVICE_MANUFACTURER} ${DEVICE_MODEL} (${DEVICE_CODENAME})"
    echo "    Codename:      ${DEVICE_PROP_VALUE}"
    echo "    Overlay:       ${OVERLAY_NAME}"
    echo "    Package:       ${OVERLAY_PACKAGE}"
    echo ""
    echo -e "  ${BOLD}Display:${NC}"
    echo "    Rounded corners: ${ROUNDED_CORNER_RADIUS}px"
    echo "    Status bar:      ${STATUS_BAR_HEIGHT}px"
    echo ""
    echo -e "  ${BOLD}Features:${NC}"
    echo "    UDFPS:           ${HAS_UDFPS}"
    echo "    AOD:             ${HAS_AOD}"
    echo "    Doze:            ${HAS_DOZE}"
    echo "    5G:              ${HAS_5G}"
    echo "    VoLTE:           ${HAS_VOLTE}"
    echo ""
    echo -e "  ${BOLD}Builder:${NC}"
    echo "    Android:         ${ANDROID_VERSION} (API ${COMPILE_SDK_VERSION})"
    echo ""
    echo -e "  ${YELLOW}Are these values correct for your device?${NC}"
    read -r -p "  [Y/n] " confirm_values

    if [[ "$confirm_values" =~ ^[Nn] ]]; then
        echo ""
        echo -e "  ${YELLOW}→${NC} Edit config.env with the correct values, then re-run: ${BOLD}./build.sh${NC}"
        echo ""
        exit 0
    fi
    echo ""
fi

echo -e "${BOLD}"
echo "  ╔══════════════════════════════════════════════════════╗"
echo "  ║           Treble Overlay Builder                     ║"
echo "  ╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo "  Device:    ${BOLD}${DEVICE_MANUFACTURER} ${DEVICE_MODEL}${NC}"
echo "  Codename:  ${DEVICE_CODENAME} (prop: ${DEVICE_PROP_NAME}=${DEVICE_PROP_VALUE})"
echo "  Overlay:   ${OVERLAY_NAME}"
echo "  Android:   ${ANDROID_VERSION} (API ${COMPILE_SDK_VERSION})"

# Store derived values
OVERLAY_VERSION="1.0"
OVERLAY_VERSION_CODE=1

# ---------------------------------------------------------------------------
# Backup previous configuration
# ---------------------------------------------------------------------------
step "Backing up current config"
do_backup

# ---------------------------------------------------------------------------
# Build mode selection
# ---------------------------------------------------------------------------
step "Build mode"

HAS_VENDOR_FILES=false
if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
    HAS_VENDOR_FILES=true
fi

if [ "$HAS_VENDOR_FILES" = "true" ]; then
    echo ""
    echo -e "  ${BOLD}Vendor HAL files detected in system/vendor/${NC}"
    echo -e ""
    echo -e "  ${BOLD}[1]${NC} Overlay-only — simpler, safer, no vendor HALs"
    echo -e "  ${BOLD}[2]${NC} Include vendor HALs — for fingerprint, vibrator, etc."
    echo -e ""
    read -r -p "  Choose [1/2]: " build_mode
    if [[ "$build_mode" == "2" ]]; then
        INCLUDE_VENDOR_HALS=true
        echo -e "  ${GREEN}→${NC} Building with vendor HAL files and sepolicy.rule"
    else
        INCLUDE_VENDOR_HALS=false
        echo -e "  ${YELLOW}→${NC} Overlay-only build (vendor HALs and sepolicy.rule skipped)"
    fi
else
    INCLUDE_VENDOR_HALS=false
    echo -e "  ${YELLOW}→${NC} No vendor HAL files found — building overlay-only"
fi

# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
step "Checking dependencies"
for cmd in aapt2 zipalign apksigner; do
    command -v "$cmd" &>/dev/null || { err "Missing: $cmd — run ./setup.sh first"; exit 1; }
done
ok "All tools found"

# Determine PLATFORM_JAR location (check tools/ first, then system path)
if [ ! -f "$PLATFORM_JAR" ]; then
    # Check if it's in the tools/ directory
    if [ -f "${SCRIPT_DIR}/tools/framework-res.apk" ]; then
        PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
    elif [ -d "/data/data/com.termux" ] && [ ! -f "${SCRIPT_DIR}/tools/framework-res.apk" ]; then
        # On Termux, try to pull it if missing
        info "Running on Android (Termux) and framework-res.apk is missing."
        info "Attempting to pull from /system/framework/framework-res.apk..."
        mkdir -p "${SCRIPT_DIR}/tools"
        if cp /system/framework/framework-res.apk "${SCRIPT_DIR}/tools/framework-res.apk" 2>/dev/null; then
            PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
            ok "framework-res.apk auto-pulled successfully"
        elif su -c "cp /system/framework/framework-res.apk \"${SCRIPT_DIR}/tools/framework-res.apk\"" 2>/dev/null; then
            PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
            ok "framework-res.apk auto-pulled successfully (via su)"
        fi
    fi
fi

if [ ! -f "$PLATFORM_JAR" ]; then
    err "Platform JAR not found."
    err "Checked: config.env PLATFORM_JAR path"
    err "Also checked: tools/framework-res.apk"
    err ""
    err "Install android-framework-res or pull from device:"
    err "  adb pull /system/framework/framework-res.apk tools/"
    err ""
    err "Or run: ./setup.sh"
    exit 1
fi
ok "Platform JAR: ${PLATFORM_JAR}"

# ---------------------------------------------------------------------------
# Generate AndroidManifest.xml
# ---------------------------------------------------------------------------
step "Generating AndroidManifest.xml"

cat > AndroidManifest.xml << MANIFEST
<?xml version="1.0" encoding="utf-8"?>
<!--
    Treble Overlay — ${OVERLAY_NAME}
    Device: ${DEVICE_MANUFACTURER} ${DEVICE_MODEL} (${DEVICE_CODENAME})
    Target: Android framework resources ("android" package)
    Condition: ${DEVICE_PROP_NAME} == "${DEVICE_PROP_VALUE}"
    Generated by build.sh from config.env
-->

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE}"
    android:versionCode="${OVERLAY_VERSION_CODE}"
    android:versionName="${OVERLAY_VERSION}">

    <application
        android:extractNativeLibs="false"
        android:usesNonSdkApi="true" />

    <uses-sdk
        android:minSdkVersion="${MIN_SDK_VERSION}"
        android:targetSdkVersion="${TARGET_SDK_VERSION}" />

    <overlay
        android:targetPackage="android"
        android:priority="${OVERLAY_PRIORITY}"
        android:isStatic="true"
        android:requiredSystemPropertyName="${DEVICE_PROP_NAME}"
        android:requiredSystemPropertyValue="${DEVICE_PROP_VALUE}" />

</manifest>
MANIFEST
ok "AndroidManifest.xml generated"

cat > systemui_overlay/AndroidManifest.xml << MANIFEST_SYSTEMUI
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE_SYSTEMUI}"
    android:versionCode="1"
    android:versionName="1.0">

    <application
        android:extractNativeLibs="false"
        android:usesNonSdkApi="true" />

    <uses-sdk
        android:minSdkVersion="${COMPILE_SDK_VERSION}"
        android:targetSdkVersion="${COMPILE_SDK_VERSION}" />

    <overlay
        android:targetPackage="com.android.systemui"
        android:priority="${OVERLAY_PRIORITY_SYSTEMUI}"
        android:isStatic="true"
        android:requiredSystemPropertyName="${DEVICE_PROP_NAME}"
        android:requiredSystemPropertyValue="${DEVICE_PROP_VALUE}" />

</manifest>
MANIFEST_SYSTEMUI
ok "systemui_overlay/AndroidManifest.xml generated"

# ---------------------------------------------------------------------------
# Generate module.prop
# ---------------------------------------------------------------------------
step "Generating module.prop"

DESCRIPTION="${DEVICE_MODEL} overlay: rounded corners (${ROUNDED_CORNER_RADIUS}px)"
[ "$HAS_AOD" = "true" ] && DESCRIPTION="${DESCRIPTION}, AOD"
[ "$HAS_UDFPS" = "true" ] && DESCRIPTION="${DESCRIPTION}, UDFPS"
[ "$HAS_5G" = "true" ] && DESCRIPTION="${DESCRIPTION}, 5G"
[ "$HAS_VOLTE" = "true" ] && DESCRIPTION="${DESCRIPTION}, VoLTE"
[ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ] && DESCRIPTION="${DESCRIPTION}, fingerprint HAL"
[ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ] && DESCRIPTION="${DESCRIPTION}, vibrator HAL"

cat > module.prop << MODPROP
id=${OVERLAY_NAME}
name=Treble Overlay — ${DEVICE_MANUFACTURER} ${DEVICE_MODEL}
version=${OVERLAY_VERSION}
versionCode=${OVERLAY_VERSION_CODE}
author=${DEVICE_MANUFACTURER}
description=${DESCRIPTION}
MODPROP
ok "module.prop generated"
info "Generating Android.mk"
cat > Android.mk << ANDROIDMK
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_MODULE := ${OVERLAY_NAME}
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ${OVERLAY_NAME}.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := ${DEVICE_MANUFACTURER}
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := \$(TARGET_OUT_PRODUCT)/overlay

include \$(BUILD_PREBUILT)
ANDROIDMK
ok "Android.mk generated"

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------
step "Cleaning previous build"
rm -f "${OVERLAY_NAME}.apk" "${OVERLAY_NAME}-systemui.apk" "${OVERLAY_NAME}-ksu.zip"
rm -rf build
mkdir -p build/compiled build/apk
ok "Build directory cleaned"

# ---------------------------------------------------------------------------
# Generate auto-config XML from config.env
# ---------------------------------------------------------------------------
step "Generating resource XML from config.env"
mkdir -p res/values systemui_overlay/res/values
generate_resource_xml
generate_systemui_resource_xml

# ---------------------------------------------------------------------------
# Compile framework-res overlay
# ---------------------------------------------------------------------------
step "Compiling framework-res overlay"
aapt2 compile --dir res -o build/compiled/ 2>&1 | sed 's/^/  /' || { err "aapt2 compile failed"; exit 1; }
ok "Framework resources compiled"

# ---------------------------------------------------------------------------
# Compile SystemUI overlay
# ---------------------------------------------------------------------------
step "Compiling SystemUI overlay"
mkdir -p build/compiled_systemui
if [ -d "systemui_overlay/res" ] && [ "$(ls -A systemui_overlay/res 2>/dev/null)" ]; then
    aapt2 compile --dir systemui_overlay/res -o build/compiled_systemui/ 2>&1 | sed 's/^/  /' || { err "aapt2 compile (systemui) failed"; exit 1; }
    ok "SystemUI resources compiled"
else
    info "No SystemUI resources found — skipping SystemUI overlay"
fi

# ---------------------------------------------------------------------------
# Link framework-res overlay
# ---------------------------------------------------------------------------
step "Linking framework-res APK"
aapt2 link --manifest AndroidManifest.xml \
    -I "${PLATFORM_JAR}" \
    --auto-add-overlay \
    --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
    --compile-sdk-version-name "${ANDROID_VERSION}" \
    -o build/apk/unsigned.apk \
    build/compiled/*.flat 2>&1 | sed 's/^/  /' || { err "aapt2 link failed"; exit 1; }
ok "Framework-res APK linked"

# ---------------------------------------------------------------------------
# Link SystemUI overlay (if resources exist)
# ---------------------------------------------------------------------------
LINKED_SYSTEMUI=false
if [ -f "build/compiled_systemui/values_config.arsc.flat" ] || [ "$(ls build/compiled_systemui/*.flat 2>/dev/null | wc -l)" -gt 0 ]; then
    step "Linking SystemUI APK"
    aapt2 link --manifest systemui_overlay/AndroidManifest.xml \
        -I "${PLATFORM_JAR}" \
        --auto-add-overlay \
        --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
        --compile-sdk-version-name "${ANDROID_VERSION}" \
        -o build/apk/systemui_unsigned.apk \
        build/compiled_systemui/*.flat 2>&1 | sed 's/^/  /' || { err "aapt2 link (systemui) failed"; exit 1; }
    LINKED_SYSTEMUI=true
    ok "SystemUI APK linked"
fi

# ---------------------------------------------------------------------------
# Zipalign
# ---------------------------------------------------------------------------
step "Zipaligning APKs"
zipalign -f 4 build/apk/unsigned.apk build/apk/aligned.apk 2>&1 || { err "zipalign failed"; exit 1; }
ok "Framework-res APK aligned"

if [ "$LINKED_SYSTEMUI" = "true" ]; then
    zipalign -f 4 build/apk/systemui_unsigned.apk build/apk/systemui_aligned.apk 2>&1 || { err "zipalign (systemui) failed"; exit 1; }
    ok "SystemUI APK aligned"
fi

# ---------------------------------------------------------------------------
# Sign
# ---------------------------------------------------------------------------
step "Signing APKs"

if [ ! -f "$PLATFORM_KEY" ] || [ ! -f "$PLATFORM_CERT" ]; then
    err "Signing keys not found!"
    err "  Key:  ${PLATFORM_KEY}"
    err "  Cert: ${PLATFORM_CERT}"
    err "Update PLATFORM_KEY/PLATFORM_CERT in config.env or generate new keys"
    exit 1
fi

apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
    --v1-signing-enabled true --v2-signing-enabled true \
    --out "${OVERLAY_NAME}.apk" build/apk/aligned.apk 2>&1 | sed 's/^/  /' || { err "apksigner failed"; exit 1; }
ok "Framework-res APK signed: ${OVERLAY_NAME}.apk"

if [ "$LINKED_SYSTEMUI" = "true" ]; then
    apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
        --v1-signing-enabled true --v2-signing-enabled true \
        --out "${OVERLAY_NAME}-systemui.apk" build/apk/systemui_aligned.apk 2>&1 | sed 's/^/  /' || { err "apksigner (systemui) failed"; exit 1; }
    ok "SystemUI APK signed: ${OVERLAY_NAME}-systemui.apk"
fi

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------
step "Verifying APKs"
apksigner verify "${OVERLAY_NAME}.apk" 2>&1 | sed 's/^/  /' && ok "Framework-res APK verified" || err "Verification failed"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    apksigner verify "${OVERLAY_NAME}-systemui.apk" 2>&1 | sed 's/^/  /' && ok "SystemUI APK verified" || err "Verification failed"
fi

SIZE_FW=$(du -sh "${OVERLAY_NAME}.apk" 2>/dev/null | cut -f1)
info "Framework APK size: ${SIZE_FW}"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    SIZE_SU=$(du -sh "${OVERLAY_NAME}-systemui.apk" 2>/dev/null | cut -f1)
    info "SystemUI APK size: ${SIZE_SU}"
fi

# ---------------------------------------------------------------------------
# Build KSU/Magisk module
# ---------------------------------------------------------------------------
step "Building KSU/Magisk module"

MODULE_TMP=".module_tmp"
rm -rf "$MODULE_TMP"
mkdir -p "${MODULE_TMP}/system/product/overlay"

# Copy overlay APKs
cp "${OVERLAY_NAME}.apk" "${MODULE_TMP}/system/product/overlay/"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    cp "${OVERLAY_NAME}-systemui.apk" "${MODULE_TMP}/system/product/overlay/"
fi

# Copy module metadata
cp module.prop "${MODULE_TMP}/"

# Auto-generate customize.sh, or use user's if present at project root
if [ -f customize.sh ]; then
    cp customize.sh "${MODULE_TMP}/customize.sh" && chmod +x "${MODULE_TMP}/customize.sh"
    ok "customize.sh: using project root's customize.sh"
elif [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
    generate_customize_sh "$MODULE_TMP"
    ok "customize.sh auto-generated from vendor/ contents"
else
    # Overlay-only: simple customize.sh
    cat > "${MODULE_TMP}/customize.sh" << 'CUSTOMIZE_SIMPLE'
#!/sbin/sh
MODPATH=${0%/*}
ui_print "  Installing ${MODPATH##*/}..."
set_perm_recursive $MODPATH/system/product/overlay 0 0 0644 u:object_r:system_file:s0
ui_print "  ✓ Module installed successfully!"
CUSTOMIZE_SIMPLE
    chmod +x "${MODULE_TMP}/customize.sh"
    ok "customize.sh generated (overlay-only)"
fi

# sepolicy.rule
if [ "$INCLUDE_VENDOR_HALS" = "true" ] && [ -f sepolicy.rule ]; then
    if grep -q '^allow' sepolicy.rule 2>/dev/null; then
        RULE_COUNT=$(grep -c '^allow' sepolicy.rule)
        cp sepolicy.rule "${MODULE_TMP}/" && ok "Included sepolicy.rule (${RULE_COUNT} allow rules)"
    else
        info "sepolicy.rule has no allow rules — template only, skipping"
    fi
else
    if [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
        info "sepolicy.rule not found or has no rules — skipping"
    else
        info "sepolicy.rule skipped (overlay-only build)"
    fi
fi

# service.sh — auto-generate or use user's copy at project root
if [ -f service.sh ]; then
    # User placed a service.sh at project root — substitute placeholders
    sed -e "s/@OVERLAY_PACKAGE@/${OVERLAY_PACKAGE}/g" \
        -e "s/@OVERLAY_PACKAGE_SYSTEMUI@/${OVERLAY_PACKAGE_SYSTEMUI}/g" \
        service.sh > "${MODULE_TMP}/service.sh"
    chmod +x "${MODULE_TMP}/service.sh"
    ok "service.sh: using project root's service.sh (package: ${OVERLAY_PACKAGE})"
else
    generate_service_sh "$MODULE_TMP"
    # Substitute placeholders in the generated file
    sed -i -e "s/@OVERLAY_PACKAGE@/${OVERLAY_PACKAGE}/g" \
           -e "s/@OVERLAY_PACKAGE_SYSTEMUI@/${OVERLAY_PACKAGE_SYSTEMUI}/g" \
           "${MODULE_TMP}/service.sh"
    ok "service.sh auto-generated (package: ${OVERLAY_PACKAGE})"
fi

# ---------------------------------------------------------------------------
# Copy vendor HAL files (only if INCLUDE_VENDOR_HALS is set)
# ---------------------------------------------------------------------------
VENDOR_HALS_COPIED=false

if [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
    # Vendor HAL binaries
    if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/bin/hw"
        cp system/vendor/bin/hw/* "${MODULE_TMP}/system/vendor/bin/hw/"
        for f in system/vendor/bin/hw/*; do
            ok "Vendor HAL: $(basename "$f")"
        done
        VENDOR_HALS_COPIED=true
    fi

    # Shared libraries
    if [ -d "system/vendor/lib64" ] && [ "$(ls -A system/vendor/lib64/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/lib64"
        cp system/vendor/lib64/*.so "${MODULE_TMP}/system/vendor/lib64/" 2>/dev/null || true
        for f in system/vendor/lib64/*.so; do
            [ -f "$f" ] && ok "Vendor lib: $(basename "$f")"
        done
    fi

    # Init .rc files
    if [ -d "system/vendor/etc/init" ] && [ "$(ls -A system/vendor/etc/init/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/etc/init"
        cp system/vendor/etc/init/* "${MODULE_TMP}/system/vendor/etc/init/"
        ok "Included $(ls system/vendor/etc/init/* 2>/dev/null | wc -l) init .rc files"
    fi

    # VINTF manifest fragments
    if [ -d "system/vendor/etc/vintf/manifest" ] && [ "$(ls -A system/vendor/etc/vintf/manifest/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/etc/vintf/manifest"
        cp system/vendor/etc/vintf/manifest/* "${MODULE_TMP}/system/vendor/etc/vintf/manifest/"
        ok "Included $(ls system/vendor/etc/vintf/manifest/* 2>/dev/null | wc -l) VINTF manifest files"
    fi

    if [ "$VENDOR_HALS_COPIED" = "true" ]; then
        info "Vendor HAL files included in module"
    else
        info "No vendor HAL files found — build pure overlay only"
    fi
else
    info "Vendor HAL files skipped (overlay-only build)"
fi

# ---------------------------------------------------------------------------
# Package module
# ---------------------------------------------------------------------------
cd "$MODULE_TMP"
zip -r "../${OVERLAY_NAME}-ksu.zip" . 2>&1 > /dev/null
cd "$SCRIPT_DIR"
rm -rf "$MODULE_TMP"
ok "KSU module packaged"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}  ╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}  ║              BUILD COMPLETE ✓                        ║${NC}"
echo -e "${GREEN}${BOLD}  ╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  ${BOLD}Output files:${NC}"
echo "    ${OVERLAY_NAME}.apk         $(du -sh "${OVERLAY_NAME}.apk" | cut -f1)"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    echo "    ${OVERLAY_NAME}-systemui.apk  $(du -sh "${OVERLAY_NAME}-systemui.apk" | cut -f1)"
fi
echo "    ${OVERLAY_NAME}-ksu.zip     $(du -sh "${OVERLAY_NAME}-ksu.zip" | cut -f1)"
echo ""
echo -e "  ${RED}${BOLD}⚠ IMPORTANT (KernelSU / KSU Next Users):${NC}"
echo "    - You MUST install a mount system like 'Magic Mount' for overlays to activate."
echo "    - DO NOT use 'OverlayFS' — this will likely cause a BOOTLOOP."
echo ""
echo "  ${BOLD}Deploy:${NC}"
echo "    Standard: Install ${OVERLAY_NAME}-ksu.zip via your Manager App (KernelSU/Magisk)."
echo ""
echo "    Manual (ADB):"
echo "      adb push ${OVERLAY_NAME}-ksu.zip /sdcard/"
echo "      adb shell su -c 'ksud module install /sdcard/${OVERLAY_NAME}-ksu.zip'"
echo ""
echo "  ${BOLD}Verify:${NC}"
echo "    adb shell cmd overlay list | grep ${OVERLAY_NAME#treble-overlay-}"
echo "    adb shell cmd overlay lookup ${OVERLAY_PACKAGE} android:dimen/rounded_corner_radius"
echo ""
