#!/bin/bash
# =============================================================================
# Treble Overlay Build Script
# =============================================================================
# Reads config.env for device-specific settings, then:
#   1. Backs up current config/vendor/sepolicy to YOUR BACKUPS/
#   2. Generates AndroidManifest.xml files from config.env
#   3. Generates resource XML (res/values/generated.xml) from config.env
#   4. Compiles overlay resources with aapt2
#   5. Zipaligns and signs the APKs
#   6. Auto-generates customize.sh and service.sh from config.env + vendor/
#   7. Packages a KSU/Magisk flashable module
#
# If config.env doesn't exist, the script will:
#   1. Ask if you want to use config.env.example (if found) for testing
#   2. If yes, copy it and proceed with the build
#   3. If no, generate a placeholder config and exit for you to edit
#
# Usage: ./build.sh
#
# Requirements: aapt2, zipalign, apksigner, framework-res.apk
#
# Quick setup:
#   ./setup.sh                    # Auto-downloads/installs everything
#
# Or manually (Debian/Ubuntu):
#   sudo apt install aapt android-sdk-build-tools apksigner android-framework-res
#
# Or manually (other distros):
#   See vendor_extraction_guide.md for platform-specific instructions
# =============================================================================

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Clean up editor backups ────────────────────────────────────────────────
# Some editors (like MT Manager in Termux) create .bak files. These cause
# errors during resource compilation (aapt2) and module packaging.
find . -name "*.bak" -type f -delete 2>/dev/null || true

# ── Local tools directory support ──────────────────────────────────────────
# If tools/ exists, prepend to PATH so aapt2, zipalign, apksigner are found.
# This allows setup.sh to install tools locally without sudo.
if [ -d "${SCRIPT_DIR}/tools" ]; then
    export PATH="${SCRIPT_DIR}/tools:${PATH}"
    # zipalign from build-tools needs libc++.so
    BT_LIB64=$(ls -d "${SCRIPT_DIR}/tools/android-sdk/build-tools/"*/lib64 2>/dev/null | head -1)
    if [ -n "$BT_LIB64" ] && [ -f "$BT_LIB64/libc++.so" ]; then
        export LD_LIBRARY_PATH="$BT_LIB64${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    fi
fi

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "  ${GREEN}✓${NC} $*"; }
info() { echo -e "  ${YELLOW}→${NC} $*"; }
err()  { echo -e "  ${RED}✗${NC} $*" >&2; }
step() { echo -e "\n${BOLD}━━━ $* ━━━${NC}"; }

# ── Check mode ──────────────────────────────────────────────────────────────
# If --check is passed, validate config.env and exit without building.
CHECK_MODE=false
for arg in "$@"; do
    if [ "$arg" = "--check" ]; then
        CHECK_MODE=true
    fi
done

# Store derived values
OVERLAY_VERSION="1.0"
OVERLAY_VERSION_CODE=1

# ---------------------------------------------------------------------------
# Backup helper
# ---------------------------------------------------------------------------
BACKUP_DIR="YOUR BACKUPS"
do_backup() {
    mkdir -p "$BACKUP_DIR"
    local backed_up=false
    [ -f "config.env" ]            && { cp config.env "$BACKUP_DIR/config.env";            ok "Backed up config.env";            backed_up=true; }
    [ -f "sepolicy.rule" ]         && { cp sepolicy.rule "$BACKUP_DIR/sepolicy.rule";      ok "Backed up sepolicy.rule";      backed_up=true; }
    [ -d "system/vendor" ]         && { rm -rf "$BACKUP_DIR/vendor"; cp -r system/vendor "$BACKUP_DIR/vendor"; ok "Backed up system/vendor/"; backed_up=true; }
    [ -f "customize.sh" ]          && { cp customize.sh "$BACKUP_DIR/customize.sh";        ok "Backed up customize.sh";       backed_up=true; }
    [ -f "service.sh" ]            && { cp service.sh "$BACKUP_DIR/service.sh";            ok "Backed up service.sh";         backed_up=true; }
    echo ""
    $backed_up && info "Backup saved to ${BACKUP_DIR}/" || info "Nothing to back up"
}

# ---------------------------------------------------------------------------
# Resource XML auto-generator — applies config.env values to overlay resources
# Generates res/values/generated.xml which overrides config.xml/bools.xml/dimens.xml
# ---------------------------------------------------------------------------
generate_resource_xml() {
    local gen="res/values/generated.xml"

    cat > "$gen" << 'GENEOF'
<?xml version="1.0" encoding="utf-8"?>
<!--
    Auto-generated by build.sh from config.env - DO NOT EDIT BY HAND.
    Edit config.env and re-build. Overrides values in config.xml, bools.xml,
    and dimens.xml based on your config.env settings.
-->
<resources>

GENEOF

    # ── Feature flags (bools) ────────────────────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_supportsUdfps">true</bool>
    <bool name="config_supportsScreenOffUdfps">true</bool>

GENEOF
    fi

    if [ "$HAS_AOD" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dozeAlwaysOnDisplayAvailable">true</bool>

GENEOF
    fi

    if [ "$HAS_DOZE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dozeAfterScreenOffByDefault">true</bool>
    <bool name="config_dozePulsePickup">true</bool>

GENEOF
    fi

    if [ "$HAS_AUTO_BRIGHTNESS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_automatic_brightness_available">true</bool>

GENEOF
    fi

    if [ "$HAS_BURN_IN_PROTECTION" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_enableBurnInProtection">true</bool>
    <bool name="config_statusBarBurnInProtection">true</bool>

GENEOF
    fi

    if [ "$HAS_DOUBLE_TAP_WAKE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_supportDoubleTapWake">true</bool>

GENEOF
    fi

    if [ "$HAS_HBM" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_dynamic_automatic_brightness_available">true</bool>
    <integer name="config_screenBrightnessExtendedMaximum">${BRIGHTNESS_EXTENDED_MAXIMUM}</integer>

GENEOF
    fi

    if [ "$HAS_5G" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_telephony5gNonStandalone">true</bool>

GENEOF
    fi

    if [ "$HAS_VOLTE" = "true" ]; then
        cat >> "$gen" << GENEOF
    <bool name="config_device_volte_available">true</bool>
    <bool name="config_device_vt_available">true</bool>
    <bool name="config_device_wfc_ims_available">true</bool>

GENEOF
    fi

    # ── Corner radius (dimen) — optional, skip if not set ────────────────
    if [ -n "$ROUNDED_CORNER_RADIUS" ] && [[ "$ROUNDED_CORNER_RADIUS" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <dimen name="rounded_corner_radius">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_radius_top">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_radius_bottom">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius_top">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="secondary_rounded_corner_radius_bottom">${ROUNDED_CORNER_RADIUS}.0px</dimen>
    <dimen name="rounded_corner_content_padding">0px</dimen>

GENEOF
    fi

    # ── Status bar height (dimen) — optional, skip if not set ────────────
    if [ -n "$STATUS_BAR_HEIGHT" ] && [[ "$STATUS_BAR_HEIGHT" != *"<"* ]]; then
        # If landscape height is not set, use portrait height
        local sb_land="${STATUS_BAR_HEIGHT_LANDSCAPE:-$STATUS_BAR_HEIGHT}"
        cat >> "$gen" << GENEOF
    <dimen name="status_bar_height">${STATUS_BAR_HEIGHT}.0px</dimen>
    <dimen name="status_bar_height_portrait">${STATUS_BAR_HEIGHT}.0px</dimen>
    <dimen name="status_bar_height_landscape">${sb_land}.0px</dimen>

GENEOF
    fi

    # ── Light sensor type (string) — optional, skip if not set ──────────
    if [ -n "$LIGHT_SENSOR_TYPE" ] && [[ "$LIGHT_SENSOR_TYPE" != *"<"* ]]; then
        # Escape special XML characters for string values
        local safe_sensor_type=$(echo "${LIGHT_SENSOR_TYPE}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g')
        cat >> "$gen" << GENEOF
    <string name="config_displayLightSensorType" translatable="false">${safe_sensor_type}</string>

GENEOF
    fi

    # ── Brightness (integers + float items) — optional, skip if not set ──
    if [ -n "$BRIGHTNESS_DIM" ] && [[ "$BRIGHTNESS_DIM" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <integer name="config_screenBrightnessDim">${BRIGHTNESS_DIM}</integer>
    <integer name="config_screenBrightnessDark">${BRIGHTNESS_DARK}</integer>
    <integer name="config_screenBrightnessDoze">${BRIGHTNESS_DOZE}</integer>
    <integer name="config_screenBrightnessSettingMinimum">${BRIGHTNESS_MIN}</integer>
    <integer name="config_screenBrightnessSettingDefault">${BRIGHTNESS_DEFAULT}</integer>
    <integer name="config_screenBrightnessSettingMaximum">${BRIGHTNESS_MAX}</integer>

GENEOF

        # Compute float equivalents (approximate)
        local doze_float=$(echo "scale=8; $BRIGHTNESS_DOZE / 255" | bc 2>/dev/null | sed 's/^\./0./' || echo "0.23529412")
        local dim_float=$(echo "scale=8; $BRIGHTNESS_DIM / 255" | bc 2>/dev/null | sed 's/^\./0./' || echo "0.05098039")
        local min_float=$(echo "scale=8; $BRIGHTNESS_MIN / 255" | bc 2>/dev/null | sed 's/^\./0./' || echo "0.0")
        local default_float=$(echo "scale=8; $BRIGHTNESS_DEFAULT / 255" | bc 2>/dev/null | sed 's/^\./0./' || echo "0.50196078")
        local max_float=$(echo "scale=8; $BRIGHTNESS_MAX / 255" | bc 2>/dev/null | sed 's/^\./0./' || echo "1.0")

        # Ensure even the fallback/echo values have leading zeros
        [[ "$doze_float" == .* ]] && doze_float="0${doze_float}"
        [[ "$dim_float" == .* ]] && dim_float="0${dim_float}"
        [[ "$min_float" == .* ]] && min_float="0${min_float}"
        [[ "$default_float" == .* ]] && default_float="0${default_float}"
        [[ "$max_float" == .* ]] && max_float="0${max_float}"

        # Ensure floats have a decimal point (e.g. "0" -> "0.0")
        [[ "$doze_float" != *.* ]] && doze_float="${doze_float}.0"
        [[ "$dim_float" != *.* ]] && dim_float="${dim_float}.0"
        [[ "$min_float" != *.* ]] && min_float="${min_float}.0"
        [[ "$default_float" != *.* ]] && default_float="${default_float}.0"
        [[ "$max_float" != *.* ]] && max_float="${max_float}.0"

        cat >> "$gen" << GENEOF
    <item name="config_screenBrightnessDozeFloat" format="float" type="dimen">${doze_float}</item>
    <item name="config_screenBrightnessDimFloat" format="float" type="dimen">${dim_float}</item>
    <item name="config_screenBrightnessSettingMinimumFloat" format="float" type="dimen">${min_float}</item>
    <item name="config_screenBrightnessSettingDefaultFloat" format="float" type="dimen">${default_float}</item>
    <item name="config_screenBrightnessSettingMaximumFloat" format="float" type="dimen">${max_float}</item>

GENEOF
    fi

    # ── Display Cutout (string) ──────────────────────────────────────────
    if [ -n "$DISPLAY_CUTOUT" ]; then
        # Escape special XML characters
        safe_cutout=$(echo "${DISPLAY_CUTOUT}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g')
        cat >> "$gen" << GENEOF
    <string name="config_mainBuiltInDisplayCutout" translatable="false">${safe_cutout}</string>

GENEOF
    fi

    # ── Optional Stock Bools (config.env OPTIONAL STOCK VALUES) ────────────
    # These are extracted from the user's stock product overlay APK.
    # They are commented out in config.env by default.
    for bool_var in \
        "CONFIG_FILL_MAIN_BUILTIN_DISPLAY_CUTOUT" \
        "CONFIG_POWER_DECOUPLE_INTERACTIVE_MODE_FROM_DISPLAY" \
        "CONFIG_POWER_DECOUPLE_AUTO_SUSPEND_MODE_FROM_DISPLAY" \
        "CONFIG_DISPLAY_BLANKS_AFTER_DOZE" \
        "CONFIG_DOZE_SUPPORTS_AOD_WALLPAPER" \
        "CONFIG_SUPPORT_AUDIO_SOURCE_UNPROCESSED" \
        "CONFIG_CAMERA_SOUND_FORCED" \
        "CONFIG_USE_DEV_INPUT_EVENT_FOR_AUDIO_JACK" \
        "CONFIG_WIFI_DISPLAY_SUPPORTS_PROTECTED_BUFFERS" \
        "CONFIG_CARRIER_VOLTE_AVAILABLE" \
        "CONFIG_CARRIER_VT_AVAILABLE" \
        "CONFIG_CARRIER_WFC_IMS_AVAILABLE" \
        "CONFIG_DYNAMIC_BIND_IMS" \
        "CONFIG_FORCE_PHONE_GLOBALS_CREATION" \
        "CONFIG_CARRIER_VOLTE_TTY_SUPPORTED" \
        "CONFIG_CAMERA_DOUBLE_TAP_POWER_GESTURE_ENABLED" \
        "SKIP_RESTORING_NETWORK_SELECTION" \
        "CONFIG_SWITCH_PHONE_ON_VOICE_REG_STATE_CHANGE"; do
        # Get the value from the variable whose name is in $bool_var
        val="${!bool_var}"
        if [ -n "$val" ] && [ "$val" != "<value>" ]; then
            # Convert the env-style name to the Android resource name
            # e.g., CONFIG_FILL_MAIN_BUILTIN_DISPLAY_CUTOUT → config_fillMainBuiltInDisplayCutout
            # We use a lookup map for the resource name
            case "$bool_var" in
                CONFIG_FILL_MAIN_BUILTIN_DISPLAY_CUTOUT)          res_name="config_fillMainBuiltInDisplayCutout" ;;
                CONFIG_POWER_DECOUPLE_INTERACTIVE_MODE_FROM_DISPLAY) res_name="config_powerDecoupleInteractiveModeFromDisplay" ;;
                CONFIG_POWER_DECOUPLE_AUTO_SUSPEND_MODE_FROM_DISPLAY) res_name="config_powerDecoupleAutoSuspendModeFromDisplay" ;;
                CONFIG_DISPLAY_BLANKS_AFTER_DOZE)                 res_name="config_displayBlanksAfterDoze" ;;
                CONFIG_DOZE_SUPPORTS_AOD_WALLPAPER)               res_name="config_dozeSupportsAodWallpaper" ;;
                CONFIG_SUPPORT_AUDIO_SOURCE_UNPROCESSED)           res_name="config_supportAudioSourceUnprocessed" ;;
                CONFIG_CAMERA_SOUND_FORCED)                       res_name="config_camera_sound_forced" ;;
                CONFIG_USE_DEV_INPUT_EVENT_FOR_AUDIO_JACK)        res_name="config_useDevInputEventForAudioJack" ;;
                CONFIG_WIFI_DISPLAY_SUPPORTS_PROTECTED_BUFFERS)    res_name="config_wifiDisplaySupportsProtectedBuffers" ;;
                CONFIG_CARRIER_VOLTE_AVAILABLE)                   res_name="config_carrier_volte_available" ;;
                CONFIG_CARRIER_VT_AVAILABLE)                      res_name="config_carrier_vt_available" ;;
                CONFIG_CARRIER_WFC_IMS_AVAILABLE)                 res_name="config_carrier_wfc_ims_available" ;;
                CONFIG_DYNAMIC_BIND_IMS)                          res_name="config_dynamic_bind_ims" ;;
                CONFIG_FORCE_PHONE_GLOBALS_CREATION)              res_name="config_force_phone_globals_creation" ;;
                CONFIG_CARRIER_VOLTE_TTY_SUPPORTED)               res_name="config_carrier_volte_tty_supported" ;;
                CONFIG_CAMERA_DOUBLE_TAP_POWER_GESTURE_ENABLED)   res_name="config_cameraDoubleTapPowerGestureEnabled" ;;
                SKIP_RESTORING_NETWORK_SELECTION)                 res_name="skip_restoring_network_selection" ;;
                CONFIG_SWITCH_PHONE_ON_VOICE_REG_STATE_CHANGE)    res_name="config_switch_phone_on_voice_reg_state_change" ;;
                *)                                                res_name="" ;;
            esac
            if [ -n "$res_name" ]; then
                cat >> "$gen" << GENEOF
    <bool name="${res_name}">${val}</bool>

GENEOF
            fi
        fi
    done

    # ── Optional Stock Strings ─────────────────────────────────────────────
    # CONFIG_RADIO_ACCESS_FAMILY
    if [ -n "${CONFIG_RADIO_ACCESS_FAMILY}" ] && [[ "${CONFIG_RADIO_ACCESS_FAMILY}" != *"<"* ]]; then
        safe_radio=$(echo "${CONFIG_RADIO_ACCESS_FAMILY}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g')
        cat >> "$gen" << GENEOF
    <string name="config_radio_access_family" translatable="false">${safe_radio}</string>

GENEOF
    fi

    # CONFIG_DOZE_UDFPS_LONG_PRESS_SENSOR_TYPE
    if [ -n "${CONFIG_DOZE_UDFPS_LONG_PRESS_SENSOR_TYPE}" ] && [[ "${CONFIG_DOZE_UDFPS_LONG_PRESS_SENSOR_TYPE}" != *"<"* ]]; then
        safe_sensor=$(echo "${CONFIG_DOZE_UDFPS_LONG_PRESS_SENSOR_TYPE}" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&apos;/g')
        cat >> "$gen" << GENEOF
    <string name="config_dozeUdfpsLongPressSensorType" translatable="false">${safe_sensor}</string>

GENEOF
    fi

    # ── Biometric Sensors (string-array) ───────────────────────────────────
    # CONFIG_BIOMETRIC_SENSORS is a semicolon-separated list of sensor specs
    # e.g., "0:2:15" for a single sensor, "0:2:15;1:8:4095" for multiple
    if [ -n "${CONFIG_BIOMETRIC_SENSORS}" ] && [[ "${CONFIG_BIOMETRIC_SENSORS}" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <string-array name="config_biometric_sensors">
GENEOF
        IFS=';' read -ra sensors <<< "${CONFIG_BIOMETRIC_SENSORS}"
        for s in "${sensors[@]}"; do
            s_trimmed=$(echo "$s" | xargs)
            [ -n "$s_trimmed" ] && echo "        <item>${s_trimmed}</item>" >> "$gen"
        done
        cat >> "$gen" << GENEOF
    </string-array>

GENEOF
    fi

    # ── Auto-brightness Arrays (space-separated values) ─────────────────────
    # AUTO_BRIGHTNESS_LEVELS and AUTO_BRIGHTNESS_BACKLIGHT_VALUES
    if [ -n "${AUTO_BRIGHTNESS_LEVELS}" ] && [[ "${AUTO_BRIGHTNESS_LEVELS}" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <integer-array name="config_autoBrightnessLevels">
GENEOF
        IFS=' ' read -ra levels <<< "${AUTO_BRIGHTNESS_LEVELS}"
        for v in "${levels[@]}"; do
            v_trimmed=$(echo "$v" | xargs)
            [ -n "$v_trimmed" ] && echo "        <item>${v_trimmed}</item>" >> "$gen"
        done
        cat >> "$gen" << GENEOF
    </integer-array>

GENEOF
    fi

    if [ -n "${AUTO_BRIGHTNESS_BACKLIGHT_VALUES}" ] && [[ "${AUTO_BRIGHTNESS_BACKLIGHT_VALUES}" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <integer-array name="config_autoBrightnessLcdBacklightValues">
GENEOF
        IFS=' ' read -ra values <<< "${AUTO_BRIGHTNESS_BACKLIGHT_VALUES}"
        for v in "${values[@]}"; do
            v_trimmed=$(echo "$v" | xargs)
            [ -n "$v_trimmed" ] && echo "        <item>${v_trimmed}</item>" >> "$gen"
        done
        cat >> "$gen" << GENEOF
    </integer-array>

GENEOF
    fi

    # ── Refresh rate (integers) — optional, skip if not set ──────────────
    if [ -n "$DEFAULT_REFRESH_RATE" ] && [[ "$DEFAULT_REFRESH_RATE" != *"<"* ]]; then
        cat >> "$gen" << GENEOF
    <integer name="config_defaultRefreshRate">${DEFAULT_REFRESH_RATE}</integer>
    <integer name="config_defaultPeakRefreshRate">${PEAK_REFRESH_RATE}</integer>

GENEOF
    fi

    # ── UDFPS sensor position (integer-array) ────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$gen" << GENEOF
    <integer-array name="config_udfps_sensor_props">
        <item>${UDFPS_X}</item>
        <item>${UDFPS_Y}</item>
        <item>${UDFPS_RADIUS}</item>
    </integer-array>

GENEOF
    fi

    # Close resources
    echo "</resources>" >> "$gen"

    local val_count=$(grep -c '<\(bool\|dimen\|integer\|string\|item\|integer-array\) ' "$gen" 2>/dev/null || echo "0")
    ok "Generated: res/values/generated.xml (${val_count} resource values from config.env)"
}

# ---------------------------------------------------------------------------
# SystemUI overlay resource generator
# Generates systemui_overlay/res/values/generated.xml for doze/AOD behavior
# ---------------------------------------------------------------------------
generate_systemui_resource_xml() {
    local gen="systemui_overlay/res/values/generated.xml"
    mkdir -p "$(dirname "$gen")"

    # doze_display_state_supported: true if HAS_AOD, else false
    local doze_state
    local doze_suspend_state

    if [ "$HAS_AOD" = "true" ]; then
        doze_state="true"
    else
        doze_state="false"
    fi

    # doze_suspend_display_state_supported: false if DOZE_SUSPEND is broken
    # (Samsung hwcomposer issue). Set DOZE_SUSPEND_UNSUPPORTED=true in config.env
    if [ "$DOZE_SUSPEND_UNSUPPORTED" = "true" ]; then
        doze_suspend_state="false"
    else
        doze_suspend_state="true"
    fi

    cat > "$gen" << GENEOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by build.sh from config.env - DO NOT EDIT BY HAND. -->
<resources>
    <bool name="doze_display_state_supported">${doze_state}</bool>
    <bool name="doze_suspend_display_state_supported">${doze_suspend_state}</bool>
    <bool name="doze_proximity_check_before_pulse">false</bool>
    <bool name="doze_pickup_performs_proximity_check">false</bool>
</resources>
GENEOF

    local sysui_count=$(grep -c '<bool ' "$gen" 2>/dev/null || echo "0")
    ok "Generated: systemui_overlay/res/values/generated.xml (${sysui_count} resource values)"
}

# ---------------------------------------------------------------------------
# Service.sh auto-generator — creates post-boot init script from config.env
# ---------------------------------------------------------------------------
generate_service_sh() {
    local target="$1"

    cat > "$target/service.sh" << 'SERVEOF'
#!/sbin/sh
# =============================================================================
# Treble Overlay — Post-Boot Initialization Script
# =============================================================================
# Auto-generated by build.sh from config.env.
# Edit config.env and re-build to change these values.
#
# For vendor-specific additions (Samsung IMS, custom HAL startup, etc.):
#   Place a service.sh at the project root with your customizations.
#   build.sh will detect it and use it instead of auto-generating.
#   See service.sh.example for a reference (Samsung Galaxy A90 5G).
# =============================================================================

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 1: Wait for boot
# ═══════════════════════════════════════════════════════════════════════════
SERVEOF

    cat >> "$target/service.sh" << 'SERVEOF'
while [ "$(getprop sys.boot_completed)" != "1" ]; do
    sleep 5
done

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 2: Enable overlays
# ═══════════════════════════════════════════════════════════════════════════
cmd overlay enable @OVERLAY_PACKAGE@ 2>/dev/null || true
cmd overlay enable @OVERLAY_PACKAGE_SYSTEMUI@ 2>/dev/null || true

SERVEOF

    # ── SECTION 3: AOD / Doze ──────────────────────────────────────────────
    if [ "$HAS_AOD" = "true" ] || [ "$HAS_DOZE" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 3: AOD / Doze configuration
# ═══════════════════════════════════════════════════════════════════════════
setprop persist.sys.overlay.aod true
setprop persist.sys.phh.disable_display_doze_suspend true

SERVEOF
    fi

    # ── SECTION 4: UDFPS properties ─────────────────────────────────────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 4: UDFPS Fingerprint properties
# ═══════════════════════════════════════════════════════════════════════════
setprop persist.sys.udfps.custom 1
SERVEOF

        cat >> "$target/service.sh" << SERVEOF
setprop persist.sys.udfps.x ${UDFPS_X}
setprop persist.sys.udfps.y ${UDFPS_Y}
setprop persist.sys.udfps.size ${UDFPS_RADIUS}

SERVEOF

        # Samsung-specific fingerprint flag
        if [ "$HAS_SAMSUNG_FINGERPRINT" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.sys.phh.samsung_fingerprint 1

SERVEOF
        fi
    fi

    # ── SECTION 5: Vendor HAL services ──────────────────────────────────────
    local has_hal=false
    if [ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ] || [ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ]; then
        has_hal=true
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 5: Vendor HAL services
# ═══════════════════════════════════════════════════════════════════════════
# Start vendor HAL services if their binaries exist in the module.
# Add custom HAL starts here or place a service.sh at project root.
# =========================================================================

# Scan for available HAL binaries and start their services.
# Service names are derived from .rc files in system/vendor/etc/init/.
SERVEOF

        if [ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
# --- Fingerprint HAL ---
# Uncomment and adjust the binary path to match YOUR device's fingerprint HAL.
# Reference: /system/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.3-service.samsung
for fp_hal in /system/vendor/bin/hw/android.hardware.biometrics.fingerprint*; do
    if [ -f "$fp_hal" ]; then
        # Try common service names
        for svc in vendor.fps_hal_aosp vendor.fps_hal vendor.fingerprint; do
            /system/bin/start "$svc" 2>/dev/null && break || true
        done
    fi
    break
done 2>/dev/null || true

SERVEOF
        fi

        if [ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
# --- Vibrator HAL ---
# Uncomment and adjust for your device's vibrator HAL.
# Reference: /system/vendor/bin/hw/vendor.samsung.hardware.vibrator@2.2-service
for vib_hal in /system/vendor/bin/hw/*vibrat*; do
    if [ -f "$vib_hal" ]; then
        for svc in sec-vibrator-2-2 vendor.vibrator vibrator; do
            /system/bin/start "$svc" 2>/dev/null && break || true
        done
    fi
    break
done 2>/dev/null || true

SERVEOF
        fi
    fi

    # ── SECTION 6: Samsung FOD (Fingerprint on Display) enable ───────────────
    if [ "$HAS_SAMSUNG_FOD" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 6: Samsung FOD (Fingerprint on Display) enable
# ═══════════════════════════════════════════════════════════════════════════
# Enables FOD mode on the TSP (Touch Screen Panel). The TSP driver lights
# up the sensor area when the fingerprint HAL activates. Without this,
# the sensor area stays dark and UDFPS will not work.

TSP_SYS="/sys/class/sec/tsp/cmd"
if [ -f "$TSP_SYS" ]; then
    chmod 0660 "$TSP_SYS" 2>/dev/null || true
    if echo "fod_enable,1" > "$TSP_SYS" 2>/dev/null; then
        log -t "treble-overlay" "  ✓ FOD enabled via $TSP_SYS" || true
        setprop persist.sys.phh.fod_enabled 1
    else
        log -t "treble-overlay" "  ✗ Failed to write FOD enable (SELinux?)" || true
    fi
else
    log -t "treble-overlay" "  - TSP sysfs not found at $TSP_SYS" || true
fi

SERVEOF
    fi

    # ── SECTION 7: Samsung Vibrator HAL start ────────────────────────────────
    if [ "$HAS_SAMSUNG_VIBRATOR" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 7: Samsung Vibrator HAL — start existing vendor service
# ═══════════════════════════════════════════════════════════════════════════
# Stock Samsung vendor has vibrator HAL at:
#   /vendor/bin/hw/vendor.samsung.hardware.vibrator@2.2-service
# Service name: sec-vibrator-2-2 (defined in vendor/etc/init/*.rc)

VIB_SERVICE="sec-vibrator-2-2"

if [ -n "$(getprop init.svc.$VIB_SERVICE 2>/dev/null)" ]; then
    if [ "$(getprop init.svc.$VIB_SERVICE)" != "running" ]; then
        log -t "treble-overlay" "  Starting: $VIB_SERVICE" || true
        start $VIB_SERVICE 2>/dev/null || true
        sleep 1
        if [ "$(getprop init.svc.$VIB_SERVICE)" = "running" ]; then
            log -t "treble-overlay" "  ✓ Vibrator HAL started" || true
            setprop persist.sys.phh.vibrator_started 1
        else
            log -t "treble-overlay" "  ✗ Vibrator HAL failed to start" || true
        fi
    else
        log -t "treble-overlay" "  ✓ Vibrator HAL already running" || true
        setprop persist.sys.phh.vibrator_started 1
    fi
fi

SERVEOF
    fi

    # ── SECTION 8: Samsung device node permissions for fingerprint ───────────
    if [ "$HAS_UDFPS" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 8: Samsung device node permissions for fingerprint
# ═══════════════════════════════════════════════════════════════════════════
# These are normally done by vendor/etc/init/fingerprint_common.rc
# on the `on boot` trigger. On GSIs, we set them here to be safe.

# Samsung ESFP (Exynos Security FingerPrint) device node
if [ -e "/dev/esfp0" ]; then
    chmod 0660 /dev/esfp0 2>/dev/null || true
    chown system system /dev/esfp0 2>/dev/null || true
fi

# Goodix fingerprint device node
if [ -e "/dev/goodix_fp" ]; then
    chmod 0660 /dev/goodix_fp 2>/dev/null || true
    chown system system /dev/goodix_fp 2>/dev/null || true
fi

# Sysfs fingerprint node ownership
FP_SYSFS="/sys/class/fingerprint/fingerprint"
if [ -d "$FP_SYSFS" ]; then
    for node in type_check name vendor adm bfs_values position cbgecnt intcnt resetcnt wuhbtest rb; do
        if [ -f "$FP_SYSFS/$node" ]; then
            chown system radio "$FP_SYSFS/$node" 2>/dev/null || true
        fi
    done
fi

# Data directories for fingerprint template storage
for dir in /data/vendor/misc /data/vendor/misc/qti_fp /data/vendor/misc/qti_fp/bg_estimation /data/vendor/misc/qti_fp/calib_test /data/vendor/misc/qti_fp/template /data/vendor/biometrics /data/vendor/fpSnrTest; do
    [ -d "$dir" ] && chmod 0770 "$dir" 2>/dev/null || true
done

SERVEOF
    fi

    # ── SECTION 9: Connectivity (5G / VoLTE) ────────────────────────────────
    if [ "$HAS_5G" = "true" ] || [ "$HAS_VOLTE" = "true" ]; then
        cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 9: Connectivity (5G / VoLTE)
# ═══════════════════════════════════════════════════════════════════════════
SERVEOF

        if [ "$HAS_5G" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.sys.phh.force_display_5g 1
setprop persist.sys.phh.radio.nr 1

SERVEOF
        fi

        if [ "$HAS_VOLTE" = "true" ]; then
            cat >> "$target/service.sh" << 'SERVEOF'
setprop persist.dbg.volte_avail_ovr 1
setprop persist.dbg.allow_ims_off 0
settings put global preferred_network_mode 26

SERVEOF
        fi
    fi

    # ── SECTION 10: Brightness / panel-specific fixes ───────────────────────
    # This section is generic — Samsung users should add full_brightness
    # via a custom service.sh at project root or service.sh.example.
    cat >> "$target/service.sh" << 'SERVEOF'
# ═══════════════════════════════════════════════════════════════════════════
# SECTION 10: Device-specific properties
# ═══════════════════════════════════════════════════════════════════════════
# Add vendor-specific setprop calls below.
# For Samsung panels, uncomment:
#   setprop persist.sys.samsung.full_brightness true
#   setprop persist.sys.qcom-brightness -1
# =========================================================================

SERVEOF

    # Close
    chmod +x "$target/service.sh"
    local svc_count=5
    [ "$HAS_UDFPS" = "true" ] && svc_count=$((svc_count + 2))
    [ "$HAS_AOD" = "true" ] && svc_count=$((svc_count + 1))
    [ "$HAS_5G" = "true" ] && svc_count=$((svc_count + 1))
    [ "$HAS_VOLTE" = "true" ] && svc_count=$((svc_count + 1))
    [ "$has_hal" = "true" ] && svc_count=$((svc_count + 1))

    info "service.sh auto-generated (${svc_count} sections)"
}

# ---------------------------------------------------------------------------
# customize.sh auto-generator
# ---------------------------------------------------------------------------
generate_customize_sh() {
    local target="$1"
    cat > "$target/customize.sh" << 'CUSTOMIZE_EOF'
#!/sbin/sh
# =============================================================================
# Treble Overlay — KSU/Magisk Module Install Script
# =============================================================================
# Auto-generated by build.sh from system/vendor/ contents.
# Edit the template in "TEMPLATE RECOVERIES (Don't touch)/customize.sh"
# and place it at project root if you need custom SELinux contexts.
# =============================================================================

MODPATH=${0%/*}

ui_print "  Installing ${MODPATH##*/}..."

# ── Overlay APKs ──────────────────────────────────────────────────────────
set_perm_recursive $MODPATH/system/product/overlay 0 0 0644 u:object_r:system_file:s0

CUSTOMIZE_EOF

    # Vendor HAL binaries
    if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_BIN'

# ── Vendor HAL binaries ───────────────────────────────────────────────────
CUSTOMIZE_BIN
        for f in system/vendor/bin/hw/*; do
            [ -f "$f" ] || continue
            local name
            name=$(basename "$f")
            cat >> "$target/customize.sh" << CUSTOMIZE_BIN_ITEM
if [ -f "\\$MODPATH/system/vendor/bin/hw/$name" ]; then
    set_perm \\$MODPATH/system/vendor/bin/hw/$name 0 2000 0755 u:object_r:vendor_file:s0
    ui_print "  • HAL: $name"
fi

CUSTOMIZE_BIN_ITEM
        done
    fi

    # Shared libraries
    if [ -d "system/vendor/lib64" ] && [ "$(ls -A system/vendor/lib64/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_LIB'

# ── Shared libraries ──────────────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/lib64" ]; then
    set_perm_recursive $MODPATH/system/vendor/lib64 0 0 0644 u:object_r:vendor_file:s0
    ui_print "  • Vendor shared libraries set"
fi

CUSTOMIZE_LIB
    fi

    # Init .rc files
    if [ -d "system/vendor/etc/init" ] && [ "$(ls -A system/vendor/etc/init/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_RC'

# ── Init .rc files ────────────────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/etc/init" ]; then
    for rc in $MODPATH/system/vendor/etc/init/*.rc; do
        [ -f "$rc" ] && set_perm "$rc" 0 0 0644 u:object_r:vendor_configs_file:s0
    done
    ui_print "  • Init .rc files set ($(ls $MODPATH/system/vendor/etc/init/*.rc 2>/dev/null | wc -l) files)"
fi

CUSTOMIZE_RC
    fi

    # VINTF manifest fragments
    if [ -d "system/vendor/etc/vintf/manifest" ] && [ "$(ls -A system/vendor/etc/vintf/manifest/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        cat >> "$target/customize.sh" << 'CUSTOMIZE_VINTF'

# ── VINTF manifest fragments ──────────────────────────────────────────────
if [ -d "$MODPATH/system/vendor/etc/vintf/manifest" ]; then
    for xml in $MODPATH/system/vendor/etc/vintf/manifest/*.xml; do
        [ -f "$xml" ] && set_perm "$xml" 0 0 0644 u:object_r:vendor_configs_file:s0
    done
    ui_print "  • VINTF manifest files set ($(ls $MODPATH/system/vendor/etc/vintf/manifest/*.xml 2>/dev/null | wc -l) files)"
fi

CUSTOMIZE_VINTF
    fi

    # Done banner
    cat >> "$target/customize.sh" << 'CUSTOMIZE_END'

# ── Done ──────────────────────────────────────────────────────────────────
ui_print "  ✓ Module installed successfully!"
CUSTOMIZE_END

    chmod +x "$target/customize.sh"
}

# ---------------------------------------------------------------------------
# Load or create config
# ---------------------------------------------------------------------------
CONFIG_FILE="config.env"

if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "\n${YELLOW}No config.env found.${NC}\n"

    USE_EXAMPLE=false
    if [ -f "config.env.example" ]; then
        echo -e "  ${BOLD}Use example config (config.env.example) for testing?${NC}"
        echo -e "  This will pre-fill values for the Samsung Galaxy A90 5G as a reference."
        read -r -p "  [y/N] " use_example
        echo ""
        if [[ "$use_example" =~ ^[Yy]$ ]]; then
            cp config.env.example config.env
            echo -e "  ${GREEN}✓${NC} Copied config.env.example → config.env"
            echo -e "  ${YELLOW}→${NC} Proceeding with build using example values...\n"
            USE_EXAMPLE=true
        fi
    fi

    if [ "$USE_EXAMPLE" != "true" ]; then
        echo -e "  ${YELLOW}Generating placeholder config.env — edit it for YOUR device, then re-run.${NC}\n"

        cat > "$CONFIG_FILE" << 'DEFAULT_CONFIG'
# =============================================================================
# Treble Overlay — Device Configuration
# =============================================================================
# Edit this file to match YOUR device, then run: ./build.sh
#
# Steps:
#   1. Change OVERLAY_NAME to something unique for your device
#   2. Set DEVICE_PROP_VALUE to your device's codename
#   3. Adjust display/UDFPS values for your hardware
#   4. Set feature flags for your device
#   5. Optionally add vendor HAL files (see vendor_extraction_guide.md)
#   6. Run: ./build.sh
#
# Example reference: Samsung Galaxy A90 5G — see config.env.example
# =============================================================================

OVERLAY_NAME="treble-overlay-<device_manufacturer>-<device_codename>"
OVERLAY_PACKAGE="me.phh.treble.overlay.<device_codename>"
OVERLAY_PACKAGE_SYSTEMUI="me.phh.treble.overlay.<device_codename>.systemui"
DEVICE_PROP_NAME="ro.product.device"
DEVICE_PROP_VALUE="<device_codename>"
OVERLAY_PRIORITY=628
OVERLAY_PRIORITY_SYSTEMUI=9999
DEVICE_MANUFACTURER="<device_manufacturer>"
DEVICE_MODEL="<device_model>"
DEVICE_CODENAME="<device_codename>"
ROUNDED_CORNER_RADIUS=100
STATUS_BAR_HEIGHT=76
HAS_UDFPS=false
UDFPS_X=540
UDFPS_Y=2145
UDFPS_RADIUS=114
HAS_SAMSUNG_FINGERPRINT=false
HAS_AUTO_BRIGHTNESS=true
LIGHT_SENSOR_TYPE="<sensor_name>"
DEFAULT_REFRESH_RATE=60
PEAK_REFRESH_RATE=60
BRIGHTNESS_DIM=15
BRIGHTNESS_DARK=3
BRIGHTNESS_DOZE=60
BRIGHTNESS_DEFAULT=128
BRIGHTNESS_MIN=0
BRIGHTNESS_MAX=255
HAS_AOD=false
HAS_DOZE=false
DOZE_SUSPEND_UNSUPPORTED=false
HAS_5G=false
HAS_VOLTE=false
HAS_BURN_IN_PROTECTION=false
HAS_DOUBLE_TAP_WAKE=false
HAS_VENDOR_FINGERPRINT_HAL=false
HAS_VENDOR_VIBRATOR_HAL=false
PLATFORM_JAR="/usr/share/android-framework-res/framework-res.apk"
PLATFORM_KEY="keys/platform.pk8"
PLATFORM_CERT="keys/platform.x509.pem"

# ── Advanced Build Settings (DO NOT EDIT) ─────────────────────────────────
# The values below are for aapt2 dictionary compatibility (linking against 
# the Android 13 resource dictionary). 
#
# ⚠️ DO NOT CHANGE THESE to match your GSI version. 
# They are for build-time linking only and do NOT affect GSI compatibility.
# Changing them will likely cause "Resource not found" errors.
COMPILE_SDK_VERSION=35
ANDROID_VERSION="15"
MIN_SDK_VERSION=33
TARGET_SDK_VERSION=34

# ── OPTIONAL STOCK VALUES (Extract from your stock firmware) ────────────────
# See config.env.example for full docs or the TrebleDroid overlay guide:
# https://github.com/TrebleDroid/treble_experimentations/wiki/How-to-create-an-overlay%3F
#CONFIG_RADIO_ACCESS_FAMILY="GSM|WCDMA|LTE|NR"
#SKIP_RESTORING_NETWORK_SELECTION=true
#CONFIG_SWITCH_PHONE_ON_VOICE_REG_STATE_CHANGE=false
#CONFIG_BIOMETRIC_SENSORS="0:2:15"
#CONFIG_FILL_MAIN_BUILTIN_DISPLAY_CUTOUT=true
#CONFIG_POWER_DECOUPLE_INTERACTIVE_MODE_FROM_DISPLAY=true
#CONFIG_POWER_DECOUPLE_AUTO_SUSPEND_MODE_FROM_DISPLAY=true
#CONFIG_DISPLAY_BLANKS_AFTER_DOZE=false
#CONFIG_DOZE_SUPPORTS_AOD_WALLPAPER=false
#CONFIG_SUPPORT_AUDIO_SOURCE_UNPROCESSED=false
#CONFIG_CAMERA_SOUND_FORCED=false
#CONFIG_USE_DEV_INPUT_EVENT_FOR_AUDIO_JACK=true
#CONFIG_WIFI_DISPLAY_SUPPORTS_PROTECTED_BUFFERS=true
#CONFIG_CARRIER_VOLTE_AVAILABLE=true
#CONFIG_CARRIER_VT_AVAILABLE=true
#CONFIG_CARRIER_WFC_IMS_AVAILABLE=true
#CONFIG_DYNAMIC_BIND_IMS=true
#CONFIG_FORCE_PHONE_GLOBALS_CREATION=true
#CONFIG_CARRIER_VOLTE_TTY_SUPPORTED=true
#CONFIG_CAMERA_DOUBLE_TAP_POWER_GESTURE_ENABLED=false
#CONFIG_DOZE_UDFPS_LONG_PRESS_SENSOR_TYPE="org.lineageos.sensor.udfps"
#AUTO_BRIGHTNESS_LEVELS="1 5 10 50 100 500 1000 3000 5000 10000 20000 40000"
#AUTO_BRIGHTNESS_BACKLIGHT_VALUES="5 15 30 60 100 140 175 210 230 245 250 255"
DEFAULT_CONFIG

        echo -e "  ${YELLOW}→${NC} Created ${BOLD}$CONFIG_FILE${NC} with placeholder values."
        echo -e "  ${YELLOW}→${NC} Edit it for your device, then re-run: ${BOLD}./build.sh${NC}"
        exit 0
    fi
fi

source "$CONFIG_FILE"

# ── Auto-generate identity strings ─────────────────────────────────────────
# Users only need to set DEVICE_CODENAME and DEVICE_MANUFACTURER
[ -z "$DEVICE_MANUFACTURER" ] || [[ "$DEVICE_MANUFACTURER" == *"<"* ]] && DEVICE_MANUFACTURER="generic"
[ -z "$DEVICE_CODENAME" ]     || [[ "$DEVICE_CODENAME" == *"<"* ]]     && DEVICE_CODENAME="generic"

# Clean manufacturer for Java package names (lowercase alphanumeric only)
SAFE_MANUFACTURER=$(echo "${DEVICE_MANUFACTURER}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')

# Clean codename for package name: replace non-alphanumeric with dots
# e.g. "Infinix-X6852" → "infinix.x6852" (dots are valid Java package separators)
PACKAGE_SEGMENT=$(echo "${DEVICE_CODENAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/./g' | sed 's/\.\.*/./g' | sed 's/^\.//;s/\.$//')

[ -z "$OVERLAY_NAME" ]        || [[ "$OVERLAY_NAME" == *"<"* ]]        && OVERLAY_NAME="treble-overlay-${DEVICE_MANUFACTURER}-${DEVICE_CODENAME}"
[ -z "$OVERLAY_PACKAGE" ]     || [[ "$OVERLAY_PACKAGE" == *"<"* ]]     && OVERLAY_PACKAGE="me.phh.treble.overlay.${SAFE_MANUFACTURER}.${PACKAGE_SEGMENT}"
[ -z "$OVERLAY_PACKAGE_SYSTEMUI" ] || [[ "$OVERLAY_PACKAGE_SYSTEMUI" == *"<"* ]] && OVERLAY_PACKAGE_SYSTEMUI="${OVERLAY_PACKAGE}.systemui"
[ -z "$DEVICE_PROP_VALUE" ]   || [[ "$DEVICE_PROP_VALUE" == *"<"* ]]   && DEVICE_PROP_VALUE="${DEVICE_CODENAME}"
[ -z "$DEVICE_PROP_NAME" ]    || [[ "$DEVICE_PROP_NAME" == *"<"* ]]    && DEVICE_PROP_NAME="ro.product.device"

[ -z "$ANDROID_VERSION" ]     && ANDROID_VERSION="14"
[ -z "$COMPILE_SDK_VERSION" ] && COMPILE_SDK_VERSION="34"
[ -z "$MIN_SDK_VERSION" ]     && MIN_SDK_VERSION="34"
[ -z "$TARGET_SDK_VERSION" ]  && TARGET_SDK_VERSION="34"
[ -z "$OVERLAY_VERSION" ]     && OVERLAY_VERSION="1.0"
[ -z "$OVERLAY_VERSION_CODE" ] && OVERLAY_VERSION_CODE="1"

[[ "${LIGHT_SENSOR_TYPE}" == *"<"* ]] && LIGHT_SENSOR_TYPE="android.sensor.light"
[[ "${DEVICE_MODEL}" == *"<"* ]] && DEVICE_MODEL="Generic Device"
# Status bar landscape height: only set fallback if explicitly a placeholder
# (otherwise leave empty so the status bar section skips it)
[[ "${STATUS_BAR_HEIGHT_LANDSCAPE}" == *"<"* ]] && STATUS_BAR_HEIGHT_LANDSCAPE=24

# Validate required values
[ -z "$DEVICE_CODENAME" ] && { err "DEVICE_CODENAME not set in config.env"; exit 1; }
[ -z "$DEVICE_MANUFACTURER" ] && { err "DEVICE_MANUFACTURER not set in config.env"; exit 1; }

# ---------------------------------------------------------------------------
# Device identity check — only check the key codename values
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Device identity check
# ---------------------------------------------------------------------------
# All identity values are filled — show summary and confirm
echo ""
echo -e "  ${GREEN}┌──────────────────────────────────────────────────────────┐${NC}"
echo -e "  ${GREEN}│${NC}  Device configuration detected                       ${GREEN}│${NC}"
echo -e "  ${GREEN}└──────────────────────────────────────────────────────────┘${NC}"
echo -e ""
echo -e "  ${BOLD}Identity:${NC}"
echo -e "    Device:        ${DEVICE_MANUFACTURER} ${DEVICE_MODEL} (${DEVICE_CODENAME})"
echo -e "    Codename:      ${DEVICE_PROP_VALUE}"
echo -e "    Overlay:       ${OVERLAY_NAME}"
echo -e "    Package:       ${OVERLAY_PACKAGE}"
echo -e ""
echo -e "  ${BOLD}Display:${NC}"
[ -n "$ROUNDED_CORNER_RADIUS" ] && [[ "$ROUNDED_CORNER_RADIUS" != *"<"* ]] && echo -e "    Rounded corners: ${ROUNDED_CORNER_RADIUS}px"
[ -n "$STATUS_BAR_HEIGHT" ] && [[ "$STATUS_BAR_HEIGHT" != *"<"* ]] && echo -e "    Status bar:      ${STATUS_BAR_HEIGHT}px"
echo -e ""
echo -e "  ${BOLD}Features:${NC}"
echo -e "    UDFPS:           ${HAS_UDFPS}"
echo -e "    AOD:             ${HAS_AOD}"
echo -e "    Doze:            ${HAS_DOZE}"
echo -e "    5G:              ${HAS_5G}"
echo -e "    VoLTE:           ${HAS_VOLTE}"
echo -e ""
echo -e "  ${BOLD}Builder:${NC}"
echo -e "    Android:         ${ANDROID_VERSION} (API ${COMPILE_SDK_VERSION})"
echo ""

# Check mode — validate and exit
if [ "$CHECK_MODE" = "true" ]; then
    echo ""
    echo -e "  ${GREEN}✓${NC} Config validation passed"
    echo -e "  ${YELLOW}→${NC} Run without --check to build"
    echo ""
    exit 0
fi

echo -e "  ${YELLOW}Are these values correct for your device?${NC}"
read -r -p "  [Y/n] " confirm_values

if [[ "$confirm_values" =~ ^[Nn] ]]; then
    echo ""
    echo -e "  ${YELLOW}→${NC} Edit config.env with the correct values, then re-run: ${BOLD}./build.sh${NC}"
    echo ""
    exit 0
fi

# ---------------------------------------------------------------------------
# Build mode selection
# ---------------------------------------------------------------------------
step "Build mode"

HAS_VENDOR_FILES=false
if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
    echo -e ""
    echo -e "  ${BOLD}[1]${NC} Overlay-only — simpler, safer, no vendor HALs"
    echo -e "  ${BOLD}[2]${NC} Include vendor HALs — for fingerprint, vibrator, etc."
    echo -e ""
    read -r -p "  Choose [1/2]: " build_mode
    if [[ "$build_mode" == "2" ]]; then
        INCLUDE_VENDOR_HALS=true
        echo -e "  ${GREEN}→${NC} Building with vendor HAL files and sepolicy.rule"
    else
        INCLUDE_VENDOR_HALS=false
        echo -e "  ${YELLOW}→${NC} Overlay-only build (vendor HALs and sepolicy.rule skipped)"
    fi
else
    INCLUDE_VENDOR_HALS=false
    echo -e "  ${YELLOW}→${NC} No vendor HAL files found — building overlay-only"
fi
# ---------------------------------------------------------------------------
# Dependency check
# ---------------------------------------------------------------------------
step "Checking dependencies"
for cmd in aapt2 zipalign apksigner; do
    command -v "$cmd" &>/dev/null || { err "Missing: $cmd — run ./setup.sh first"; exit 1; }
done
ok "All tools found"

# Determine PLATFORM_JAR location (check tools/ first, then system path)
if [ ! -f "$PLATFORM_JAR" ]; then
    # Check if it's in the tools/ directory
    if [ -f "${SCRIPT_DIR}/tools/framework-res.apk" ]; then
        PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
    elif [ -d "/data/data/com.termux" ] && [ ! -f "${SCRIPT_DIR}/tools/framework-res.apk" ]; then
        # On Termux, try to pull it if missing
        info "Running on Android (Termux) and framework-res.apk is missing."
        info "Attempting to pull from /system/framework/framework-res.apk..."
        mkdir -p "${SCRIPT_DIR}/tools"
        if cp /system/framework/framework-res.apk "${SCRIPT_DIR}/tools/framework-res.apk" 2>/dev/null; then
            PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
            ok "framework-res.apk auto-pulled successfully"
        elif su -c "cp /system/framework/framework-res.apk \"${SCRIPT_DIR}/tools/framework-res.apk\"" 2>/dev/null; then
            PLATFORM_JAR="${SCRIPT_DIR}/tools/framework-res.apk"
            ok "framework-res.apk auto-pulled successfully (via su)"
        fi
    fi
fi

if [ ! -f "$PLATFORM_JAR" ]; then
    err "Platform JAR not found."
    err "Checked: config.env PLATFORM_JAR path"
    err "Also checked: tools/framework-res.apk"
    err ""
    err "Install android-framework-res or pull from device:"
    err "  adb pull /system/framework/framework-res.apk tools/"
    err ""
    err "Or run: ./setup.sh"
    exit 1
fi
ok "Platform JAR: ${PLATFORM_JAR}"

# ---------------------------------------------------------------------------
# Generate AndroidManifest.xml
# ---------------------------------------------------------------------------
step "Generating AndroidManifest.xml"

cat > AndroidManifest.xml << MANIFEST
<?xml version="1.0" encoding="utf-8"?>
<!--
    Treble Overlay — ${OVERLAY_NAME}
    Device: ${DEVICE_MANUFACTURER} ${DEVICE_MODEL} (${DEVICE_CODENAME})
    Target: Android framework resources ("android" package)
    Condition: ${DEVICE_PROP_NAME} == "${DEVICE_PROP_VALUE}"
    Generated by build.sh from config.env
-->

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE}"
    android:versionCode="${OVERLAY_VERSION_CODE}"
    android:versionName="${OVERLAY_VERSION}">

    <application
        android:extractNativeLibs="false"
        android:usesNonSdkApi="true" />

    <uses-sdk
        android:minSdkVersion="${MIN_SDK_VERSION}"
        android:targetSdkVersion="${TARGET_SDK_VERSION}" />

    <overlay
        android:targetPackage="android"
        android:priority="${OVERLAY_PRIORITY}"
        android:isStatic="true"
        android:requiredSystemPropertyName="${DEVICE_PROP_NAME}"
        android:requiredSystemPropertyValue="${DEVICE_PROP_VALUE}" />

</manifest>
MANIFEST
ok "AndroidManifest.xml generated"

cat > systemui_overlay/AndroidManifest.xml << MANIFEST_SYSTEMUI
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE_SYSTEMUI}"
    android:versionCode="1"
    android:versionName="1.0">

    <application
        android:extractNativeLibs="false"
        android:usesNonSdkApi="true" />

    <uses-sdk
        android:minSdkVersion="${COMPILE_SDK_VERSION}"
        android:targetSdkVersion="${COMPILE_SDK_VERSION}" />

    <overlay
        android:targetPackage="com.android.systemui"
        android:priority="${OVERLAY_PRIORITY_SYSTEMUI}"
        android:isStatic="true"
        android:requiredSystemPropertyName="${DEVICE_PROP_NAME}"
        android:requiredSystemPropertyValue="${DEVICE_PROP_VALUE}" />

</manifest>
MANIFEST_SYSTEMUI
ok "systemui_overlay/AndroidManifest.xml generated"

# ---------------------------------------------------------------------------
# Generate module.prop
# ---------------------------------------------------------------------------
step "Generating module.prop"

DESCRIPTION="${DEVICE_MODEL} overlay"
[ -n "$ROUNDED_CORNER_RADIUS" ] && [[ "$ROUNDED_CORNER_RADIUS" != *"<"* ]] && DESCRIPTION="${DESCRIPTION}: rounded corners (${ROUNDED_CORNER_RADIUS}px)"
[ "$HAS_AOD" = "true" ] && DESCRIPTION="${DESCRIPTION}, AOD"
[ "$HAS_UDFPS" = "true" ] && DESCRIPTION="${DESCRIPTION}, UDFPS"
[ "$HAS_5G" = "true" ] && DESCRIPTION="${DESCRIPTION}, 5G"
[ "$HAS_VOLTE" = "true" ] && DESCRIPTION="${DESCRIPTION}, VoLTE"
[ "$HAS_VENDOR_FINGERPRINT_HAL" = "true" ] && DESCRIPTION="${DESCRIPTION}, fingerprint HAL"
[ "$HAS_VENDOR_VIBRATOR_HAL" = "true" ] && DESCRIPTION="${DESCRIPTION}, vibrator HAL"

cat > module.prop << MODPROP
id=${OVERLAY_NAME}
name=Treble Overlay - ${DEVICE_MANUFACTURER} ${DEVICE_MODEL}
version=${OVERLAY_VERSION}
versionCode=${OVERLAY_VERSION_CODE}
author=${DEVICE_MANUFACTURER}
description=${DESCRIPTION}
MODPROP
ok "module.prop generated"
info "Generating Android.mk"
cat > Android.mk << ANDROIDMK
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)

LOCAL_MODULE := ${OVERLAY_NAME}
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ${OVERLAY_NAME}.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := ${DEVICE_MANUFACTURER}
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := \$(TARGET_OUT_PRODUCT)/overlay

include \$(BUILD_PREBUILT)
ANDROIDMK
ok "Android.mk generated"

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------
step "Cleaning previous build"
rm -f "${OVERLAY_NAME}.apk" "${OVERLAY_NAME}-systemui.apk" "${OVERLAY_NAME}-ksu.zip" "${OVERLAY_NAME}-hardware-overlay.zip"
rm -rf build out
mkdir -p build/compiled build/apk out/apks
ok "Build directory cleaned"

# ---------------------------------------------------------------------------
# Generate auto-config XML from config.env
# ---------------------------------------------------------------------------
step "Generating resource XML from config.env"
mkdir -p res/values systemui_overlay/res/values
generate_resource_xml
generate_systemui_resource_xml

# ---------------------------------------------------------------------------
# Compile framework-res overlay
# ---------------------------------------------------------------------------
step "Compiling framework-res overlay"
aapt2 compile --dir res -o build/compiled/ 2>&1 | sed 's/^/  /' || { err "aapt2 compile failed"; exit 1; }
ok "Framework resources compiled"

# ---------------------------------------------------------------------------
# Compile SystemUI overlay
# ---------------------------------------------------------------------------
step "Compiling SystemUI overlay"
mkdir -p build/compiled_systemui
if [ -d "systemui_overlay/res" ] && [ "$(ls -A systemui_overlay/res 2>/dev/null)" ]; then
    aapt2 compile --dir systemui_overlay/res -o build/compiled_systemui/ 2>&1 | sed 's/^/  /' || { err "aapt2 compile (systemui) failed"; exit 1; }
    ok "SystemUI resources compiled"
else
    info "No SystemUI resources found — skipping SystemUI overlay"
fi

# ---------------------------------------------------------------------------
# Link framework-res overlay
# ---------------------------------------------------------------------------
step "Linking framework-res APK"
aapt2 link --manifest AndroidManifest.xml \
    -I "${PLATFORM_JAR}" \
    --auto-add-overlay \
    --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
    --compile-sdk-version-name "${ANDROID_VERSION}" \
    -o build/apk/unsigned.apk \
    build/compiled/*.flat 2>&1 | sed 's/^/  /' || { err "aapt2 link failed"; exit 1; }
ok "Framework-res APK linked"

# ---------------------------------------------------------------------------
# Link SystemUI overlay (if resources exist)
# ---------------------------------------------------------------------------
LINKED_SYSTEMUI=false
if [ -f "build/compiled_systemui/values_config.arsc.flat" ] || [ "$(ls build/compiled_systemui/*.flat 2>/dev/null | wc -l)" -gt 0 ]; then
    step "Linking SystemUI APK"
    aapt2 link --manifest systemui_overlay/AndroidManifest.xml \
        -I "${PLATFORM_JAR}" \
        --auto-add-overlay \
        --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
        --compile-sdk-version-name "${ANDROID_VERSION}" \
        -o build/apk/systemui_unsigned.apk \
        build/compiled_systemui/*.flat 2>&1 | sed 's/^/  /' || { err "aapt2 link (systemui) failed"; exit 1; }
    LINKED_SYSTEMUI=true
    ok "SystemUI APK linked"
fi

# ---------------------------------------------------------------------------
# Zipalign
# ---------------------------------------------------------------------------
step "Zipaligning APKs"
zipalign -f 4 build/apk/unsigned.apk build/apk/aligned.apk 2>&1 || { err "zipalign failed"; exit 1; }
ok "Framework-res APK aligned"

if [ "$LINKED_SYSTEMUI" = "true" ]; then
    zipalign -f 4 build/apk/systemui_unsigned.apk build/apk/systemui_aligned.apk 2>&1 || { err "zipalign (systemui) failed"; exit 1; }
    ok "SystemUI APK aligned"
fi

# ---------------------------------------------------------------------------
# Sign
# ---------------------------------------------------------------------------
step "Signing APKs"

if [ ! -f "$PLATFORM_KEY" ] || [ ! -f "$PLATFORM_CERT" ]; then
    err "Signing keys not found!"
    err "  Key:  ${PLATFORM_KEY}"
    err "  Cert: ${PLATFORM_CERT}"
    err "Update PLATFORM_KEY/PLATFORM_CERT in config.env or generate new keys"
    exit 1
fi

apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
    --v1-signing-enabled true --v2-signing-enabled true --v4-signing-enabled false \
    --out "out/apks/${OVERLAY_NAME}.apk" build/apk/aligned.apk 2>&1 | sed 's/^/  /' || { err "apksigner failed"; exit 1; }
ok "Framework-res APK signed: out/apks/${OVERLAY_NAME}.apk"

if [ "$LINKED_SYSTEMUI" = "true" ]; then
    apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
        --v1-signing-enabled true --v2-signing-enabled true --v4-signing-enabled false \
        --out "out/apks/${OVERLAY_NAME}-systemui.apk" build/apk/systemui_aligned.apk 2>&1 | sed 's/^/  /' || { err "apksigner (systemui) failed"; exit 1; }
    ok "SystemUI APK signed: out/apks/${OVERLAY_NAME}-systemui.apk"
fi

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------
step "Verifying APKs"
apksigner verify "out/apks/${OVERLAY_NAME}.apk" 2>&1 | sed 's/^/  /' && ok "Framework-res APK verified" || err "Verification failed"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    apksigner verify "out/apks/${OVERLAY_NAME}-systemui.apk" 2>&1 | sed 's/^/  /' && ok "SystemUI APK verified" || err "Verification failed"
fi

SIZE_FW=$(du -sh "out/apks/${OVERLAY_NAME}.apk" 2>/dev/null | cut -f1)
info "Framework APK size: ${SIZE_FW}"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    SIZE_SU=$(du -sh "out/apks/${OVERLAY_NAME}-systemui.apk" 2>/dev/null | cut -f1)
    info "SystemUI APK size: ${SIZE_SU}"
fi

# ---------------------------------------------------------------------------
# Build KSU/Magisk module
# ---------------------------------------------------------------------------
step "Building KSU/Magisk module"

MODULE_TMP=".module_tmp"
rm -rf "$MODULE_TMP"
mkdir -p "${MODULE_TMP}/system/product/overlay"

# Copy overlay APKs
cp "out/apks/${OVERLAY_NAME}.apk" "${MODULE_TMP}/system/product/overlay/"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    cp "out/apks/${OVERLAY_NAME}-systemui.apk" "${MODULE_TMP}/system/product/overlay/"
fi

# Copy module metadata
cp module.prop "${MODULE_TMP}/"

# Auto-generate customize.sh, or use user's if present at project root
if [ -f customize.sh ]; then
    cp customize.sh "${MODULE_TMP}/customize.sh" && chmod +x "${MODULE_TMP}/customize.sh"
    ok "customize.sh: using project root's customize.sh"
elif [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
    generate_customize_sh "$MODULE_TMP"
    ok "customize.sh auto-generated from vendor/ contents"
else
    # Overlay-only: simple customize.sh
    cat > "${MODULE_TMP}/customize.sh" << 'CUSTOMIZE_SIMPLE'
#!/sbin/sh
MODPATH=${0%/*}
ui_print "  Installing ${MODPATH##*/}..."
set_perm_recursive $MODPATH/system/product/overlay 0 0 0644 u:object_r:system_file:s0
ui_print "  ✓ Module installed successfully!"
CUSTOMIZE_SIMPLE
    chmod +x "${MODULE_TMP}/customize.sh"
    ok "customize.sh generated (overlay-only)"
fi

# sepolicy.rule
if [ "$INCLUDE_VENDOR_HALS" = "true" ] && [ -f sepolicy.rule ]; then
    if grep -q '^allow' sepolicy.rule 2>/dev/null; then
        RULE_COUNT=$(grep -c '^allow' sepolicy.rule)
        cp sepolicy.rule "${MODULE_TMP}/" && ok "Included sepolicy.rule (${RULE_COUNT} allow rules)"
    else
        info "sepolicy.rule has no allow rules — template only, skipping"
    fi
else
    if [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
        info "sepolicy.rule not found or has no rules — skipping"
    else
        info "sepolicy.rule skipped (overlay-only build)"
    fi
fi

# service.sh — auto-generate or use user's copy at project root
if [ -f service.sh ]; then
    # User placed a service.sh at project root — substitute placeholders
    sed -e "s/@OVERLAY_PACKAGE@/${OVERLAY_PACKAGE}/g" \
        -e "s/@OVERLAY_PACKAGE_SYSTEMUI@/${OVERLAY_PACKAGE_SYSTEMUI}/g" \
        service.sh > "${MODULE_TMP}/service.sh"
    chmod +x "${MODULE_TMP}/service.sh"
    ok "service.sh: using project root's service.sh (package: ${OVERLAY_PACKAGE})"
else
    generate_service_sh "$MODULE_TMP"
    # Substitute placeholders in the generated file
    sed -i -e "s/@OVERLAY_PACKAGE@/${OVERLAY_PACKAGE}/g" \
           -e "s/@OVERLAY_PACKAGE_SYSTEMUI@/${OVERLAY_PACKAGE_SYSTEMUI}/g" \
           "${MODULE_TMP}/service.sh"
    ok "service.sh auto-generated (package: ${OVERLAY_PACKAGE})"
fi

# ---------------------------------------------------------------------------
# Copy vendor HAL files (only if INCLUDE_VENDOR_HALS is set)
# ---------------------------------------------------------------------------
VENDOR_HALS_COPIED=false

if [ "$INCLUDE_VENDOR_HALS" = "true" ]; then
    # Vendor HAL binaries
    if [ -d "system/vendor/bin/hw" ] && [ "$(ls -A system/vendor/bin/hw/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/bin/hw"
        cp system/vendor/bin/hw/* "${MODULE_TMP}/system/vendor/bin/hw/"
        for f in system/vendor/bin/hw/*; do
            ok "Vendor HAL: $(basename "$f")"
        done
        VENDOR_HALS_COPIED=true
    fi

    # Shared libraries
    if [ -d "system/vendor/lib64" ] && [ "$(ls -A system/vendor/lib64/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/lib64"
        cp system/vendor/lib64/*.so "${MODULE_TMP}/system/vendor/lib64/" 2>/dev/null || true
        for f in system/vendor/lib64/*.so; do
            [ -f "$f" ] && ok "Vendor lib: $(basename "$f")"
        done
    fi

    # Init .rc files
    if [ -d "system/vendor/etc/init" ] && [ "$(ls -A system/vendor/etc/init/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/etc/init"
        cp system/vendor/etc/init/* "${MODULE_TMP}/system/vendor/etc/init/"
        ok "Included $(ls system/vendor/etc/init/* 2>/dev/null | wc -l) init .rc files"
    fi

    # VINTF manifest fragments
    if [ -d "system/vendor/etc/vintf/manifest" ] && [ "$(ls -A system/vendor/etc/vintf/manifest/ 2>/dev/null | grep -c .)" -gt 0 ]; then
        mkdir -p "${MODULE_TMP}/system/vendor/etc/vintf/manifest"
        cp system/vendor/etc/vintf/manifest/* "${MODULE_TMP}/system/vendor/etc/vintf/manifest/"
        ok "Included $(ls system/vendor/etc/vintf/manifest/* 2>/dev/null | wc -l) VINTF manifest files"
    fi

    if [ "$VENDOR_HALS_COPIED" = "true" ]; then
        info "Vendor HAL files included in module"
    else
        info "No vendor HAL files found — build pure overlay only"
    fi
else
    info "Vendor HAL files skipped (overlay-only build)"
fi

# ---------------------------------------------------------------------------
# Package module
# ---------------------------------------------------------------------------
cd "$MODULE_TMP"
zip -r "${SCRIPT_DIR}/out/${OVERLAY_NAME}-ksu.zip" . 2>&1 > /dev/null
cd "$SCRIPT_DIR"
rm -rf "$MODULE_TMP"
ok "KSU module packaged: out/${OVERLAY_NAME}-ksu.zip"

# ---------------------------------------------------------------------------
# Build Hardware Overlay Repo Structure (AOSP source-based)
# ---------------------------------------------------------------------------
step "Building Hardware Overlay Repo structure"

HW_OVERLAY_DIR="build/hardware_overlay"
rm -rf "$HW_OVERLAY_DIR"
mkdir -p "$HW_OVERLAY_DIR"

# Allow overriding props for the hardware overlay repo specifically
HW_MATCH_PROP="${HW_OVERLAY_MATCH_PROP:-$DEVICE_PROP_NAME}"
HW_MATCH_VALUE="${HW_OVERLAY_MATCH_VALUE:-$DEVICE_PROP_VALUE}"

# Helper to merge XML resources into a single file
# Usage: merge_resources <source_res_dir> <target_file>
merge_resources() {
    local src_dir="$1"
    local target="$2"
    mkdir -p "$(dirname "$target")"
    
    cat > "$target" << 'XML_EOF'
<?xml version="1.0" encoding="utf-8"?>
<resources>
XML_EOF

    # Collect all items from all xml files in values/
    # We strip the <resources> tags and combine the rest.
    # Note: This is a simple merge. If a resource is defined twice, 
    # AOSP build might still complain, but our generated.xml + others 
    # structure is usually clean enough if handled carefully.
    # To be safest, we'll exclude the original files if we know they are 
    # being overridden by generated.xml.
    
    for f in "$src_dir"/values/*.xml; do
        [ -f "$f" ] || continue
        # Filter out lines that are just <resources> or </resources> or xml declaration
        grep -vE '<\?xml|<resources>|</resources>' "$f" >> "$target"
    done

    # Deduplicate: if a resource name appears multiple times, keep only the LAST occurrence.
    # This ensures that generated.xml (which is sourced after static files) wins.
    # Use awk with a portable approach (no gawk-specific match() with 3 args).
    if command -v awk &>/dev/null; then
        local tmp="${TMPDIR:-/tmp}/rro_merge.$$"
        # Reverse the file, keep first occurrence of each resource name, then reverse back.
        awk '
            { lines[NR] = $0 }
            END {
                for (i = NR; i >= 1; i--) {
                    line = lines[i]
                    if (match(line, /name="[^"]+"/)) {
                        name = substr(line, RSTART, RLENGTH)
                        if (!seen[name]++) {
                            print line
                        }
                    } else {
                        print line
                    }
                }
            }
        ' "$target" | awk '
            { lines[NR] = $0 }
            END {
                for (i = NR; i >= 1; i--) print lines[i]
            }
        ' > "$tmp" 2>/dev/null
        # Only replace target if the tmp file has content
        if [ -s "$tmp" ]; then
            mv "$tmp" "$target"
        else
            rm -f "$tmp"
        fi
    fi
    
    echo "</resources>" >> "$target"
}

# 1. Framework Overlay
FW_HW_DIR="${HW_OVERLAY_DIR}/${DEVICE_MANUFACTURER}/${DEVICE_CODENAME}"
mkdir -p "$FW_HW_DIR"
merge_resources "res" "$FW_HW_DIR/res/values/config.xml"

# Copy non-values resources (like res/xml/power_profile.xml)
if [ -d "res/xml" ]; then
    mkdir -p "$FW_HW_DIR/res/xml"
    cp -r res/xml/* "$FW_HW_DIR/res/xml/" 2>/dev/null || true
fi

cat > "$FW_HW_DIR/Android.mk" << ANDROIDMK
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := ${OVERLAY_NAME}
LOCAL_MODULE_PATH := \$(TARGET_OUT_PRODUCT)/overlay
LOCAL_IS_RUNTIME_RESOURCE_OVERLAY := true
LOCAL_PRIVATE_PLATFORM_APIS := true
include \$(BUILD_PACKAGE)
ANDROIDMK

cat > "$FW_HW_DIR/AndroidManifest.xml" << MANIFEST
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE}"
    android:versionCode="${OVERLAY_VERSION_CODE}"
    android:versionName="${OVERLAY_VERSION}">
    <overlay android:targetPackage="android"
        android:requiredSystemPropertyName="${HW_MATCH_PROP}"
        android:requiredSystemPropertyValue="${HW_MATCH_VALUE}"
        android:priority="${OVERLAY_PRIORITY}"
        android:isStatic="true" />
</manifest>
MANIFEST

ok "Hardware Overlay (Framework) generated: ${FW_HW_DIR}"

# 2. SystemUI Overlay (if exists)
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    SYSUI_HW_DIR="${HW_OVERLAY_DIR}/${DEVICE_MANUFACTURER}/${DEVICE_CODENAME}-SystemUI"
    mkdir -p "$SYSUI_HW_DIR"
    merge_resources "systemui_overlay/res" "$SYSUI_HW_DIR/res/values/config.xml"
    
    cat > "$SYSUI_HW_DIR/Android.mk" << ANDROIDMK
LOCAL_PATH := \$(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PACKAGE_NAME := ${OVERLAY_NAME}-systemui
LOCAL_MODULE_PATH := \$(TARGET_OUT_PRODUCT)/overlay
LOCAL_IS_RUNTIME_RESOURCE_OVERLAY := true
LOCAL_PRIVATE_PLATFORM_APIS := true
include \$(BUILD_PACKAGE)
ANDROIDMK

    cat > "$SYSUI_HW_DIR/AndroidManifest.xml" << MANIFEST
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${OVERLAY_PACKAGE_SYSTEMUI}"
    android:versionCode="1"
    android:versionName="1.0">
    <overlay android:targetPackage="com.android.systemui"
        android:requiredSystemPropertyName="${HW_MATCH_PROP}"
        android:requiredSystemPropertyValue="${HW_MATCH_VALUE}"
        android:priority="${OVERLAY_PRIORITY_SYSTEMUI}"
        android:isStatic="true" />
</manifest>
MANIFEST

    ok "Hardware Overlay (SystemUI) generated: ${SYSUI_HW_DIR}"
fi

# Package it
cd "$HW_OVERLAY_DIR"
zip -r "${SCRIPT_DIR}/out/${OVERLAY_NAME}-hardware-overlay.zip" . 2>&1 > /dev/null
cd "$SCRIPT_DIR"
ok "Hardware Overlay Repo package created: out/${OVERLAY_NAME}-hardware-overlay.zip"

# 3. Build Hardware Overlay TEST Flashable Zip
# This builds an APK from the *merged* hardware overlay source and packages it
# into a simple flashable module so you can test if the AOSP repo version works.
step "Building Hardware Overlay TEST Flashable Zip"

TEST_BUILD_DIR="build/hw_test"
rm -rf "$TEST_BUILD_DIR"
mkdir -p "$TEST_BUILD_DIR/compiled" "$TEST_BUILD_DIR/apk" "$TEST_BUILD_DIR/module/system/product/overlay"

# 3a. Compile merged Framework resources
info "Building TEST Framework APK..."
aapt2 compile --dir "$FW_HW_DIR/res" -o "$TEST_BUILD_DIR/compiled/" 2>&1 | sed 's/^/  /'
aapt2 link --manifest "$FW_HW_DIR/AndroidManifest.xml" \
    -I "${PLATFORM_JAR}" \
    --auto-add-overlay \
    --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
    --compile-sdk-version-name "${ANDROID_VERSION}" \
    -o "$TEST_BUILD_DIR/apk/unsigned.apk" \
    "$TEST_BUILD_DIR/compiled"/*.flat 2>&1 | sed 's/^/  /'

zipalign -f 4 "$TEST_BUILD_DIR/apk/unsigned.apk" "$TEST_BUILD_DIR/apk/aligned.apk"
apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
    --v1-signing-enabled true --v2-signing-enabled true --v4-signing-enabled false \
    --out "$TEST_BUILD_DIR/module/system/product/overlay/${OVERLAY_NAME}.apk" "$TEST_BUILD_DIR/apk/aligned.apk"

# 3b. Compile merged SystemUI resources (if exists)
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    info "Building TEST SystemUI APK..."
    mkdir -p "$TEST_BUILD_DIR/compiled_systemui" "$TEST_BUILD_DIR/apk_systemui"
    aapt2 compile --dir "$SYSUI_HW_DIR/res" -o "$TEST_BUILD_DIR/compiled_systemui/" 2>&1 | sed 's/^/  /'
    aapt2 link --manifest "$SYSUI_HW_DIR/AndroidManifest.xml" \
        -I "${PLATFORM_JAR}" \
        --auto-add-overlay \
        --compile-sdk-version-code "${COMPILE_SDK_VERSION}" \
        --compile-sdk-version-name "${ANDROID_VERSION}" \
        -o "$TEST_BUILD_DIR/apk_systemui/unsigned.apk" \
        "$TEST_BUILD_DIR/compiled_systemui"/*.flat 2>&1 | sed 's/^/  /'
    
    zipalign -f 4 "$TEST_BUILD_DIR/apk_systemui/unsigned.apk" "$TEST_BUILD_DIR/apk_systemui/aligned.apk"
    apksigner sign --key "${PLATFORM_KEY}" --cert "${PLATFORM_CERT}" \
        --v1-signing-enabled true --v2-signing-enabled true --v4-signing-enabled false \
        --out "$TEST_BUILD_DIR/module/system/product/overlay/${OVERLAY_NAME}-systemui.apk" "$TEST_BUILD_DIR/apk_systemui/aligned.apk"
fi

# Package into test module
cp module.prop "$TEST_BUILD_DIR/module/"
sed -i "s/^name=.*/name=Treble Overlay TEST - ${DEVICE_MANUFACTURER} ${DEVICE_CODENAME}/" "$TEST_BUILD_DIR/module/module.prop"
sed -i "s/^description=.*/description=Test build of merged source overlays for Hardware Overlay Repo submission./" "$TEST_BUILD_DIR/module/module.prop"

cat > "$TEST_BUILD_DIR/module/customize.sh" << 'CUSTOM_EOF'
#!/sbin/sh
MODPATH=${0%/*}
ui_print "  Installing Hardware Overlay TEST module..."
set_perm_recursive $MODPATH/system/product/overlay 0 0 0644 u:object_r:system_file:s0
ui_print "  ✓ TEST module installed."
CUSTOM_EOF

cd "$TEST_BUILD_DIR/module"
zip -r "${SCRIPT_DIR}/out/${OVERLAY_NAME}-hardware-overlay-test.zip" . 2>&1 > /dev/null
cd "$SCRIPT_DIR"
ok "Hardware Overlay TEST module created: out/${OVERLAY_NAME}-hardware-overlay-test.zip"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}${BOLD}  ╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}  ║              BUILD COMPLETE ✓                        ║${NC}"
echo -e "${GREEN}${BOLD}  ╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  ${BOLD}Output files (out/):${NC}"
echo "    out/apks/${OVERLAY_NAME}.apk         $(du -sh "out/apks/${OVERLAY_NAME}.apk" | cut -f1)"
if [ "$LINKED_SYSTEMUI" = "true" ]; then
    echo "    out/apks/${OVERLAY_NAME}-systemui.apk  $(du -sh "out/apks/${OVERLAY_NAME}-systemui.apk" | cut -f1)"
fi
echo ""
echo "    out/${OVERLAY_NAME}-ksu.zip              (Main KSU module)"
echo "    out/${OVERLAY_NAME}-hardware-overlay.zip (For Repo submission)"
echo "    out/${OVERLAY_NAME}-hardware-overlay-test.zip (Test repo version locally)"
echo ""
echo -e "  ${RED}${BOLD}⚠ IMPORTANT (KernelSU / KSU Next Users):${NC}"
echo "    - You MUST install a mount system like 'Magic Mount' for overlays to activate."
echo "    - DO NOT use 'OverlayFS' — this will likely cause a BOOTLOOP."
echo ""
echo "  ${BOLD}Deploy:${NC}"
echo "    Standard: Install out/${OVERLAY_NAME}-ksu.zip via your Manager App."
echo ""
echo "    Manual (ADB):"
echo "      adb push out/${OVERLAY_NAME}-ksu.zip /sdcard/"
echo "      adb shell su -c 'ksud module install /sdcard/${OVERLAY_NAME}-ksu.zip'"
echo ""
echo "  ${BOLD}Verify:${NC}"
echo "    adb shell cmd overlay list | grep ${OVERLAY_NAME#treble-overlay-}"
echo "    adb shell cmd overlay lookup ${OVERLAY_PACKAGE} android:dimen/rounded_corner_radius"
echo ""
